### ISSUE TITLE
how to set up virtual machine with your nox?

### ISSUE THREAD

**Issue by darkoulis12** [rastapasta/pokemon-go-mitm#112]
i run ubuntu at virtual i make network proxy with my local ip adress and i set port 8081
also i did the same at nox
but when i run scripts from poke folder nothing happens

**Comment by halixness** [comment]
So easy :
- Root Mode > ON
- Install XPOSED INSTALLER.apk
- From Xposed go to Frameworks > Install/Update
- Follow the steps and reboot
- Install Pokemon Xposed module from github and read it with XPosed
- Go to settings > Wireless > WirelessSSID > Modify Network(longpress) > Advanced Settings > Proxy Host (machine ip running coffeescript ,Port 8081 > Save

**Comment by jmoriau** [comment]
this has absolutely nothing to do with the project, issues are not a support forum, please close this.
