### ISSUE TITLE
Windows Installation Issues?

### ISSUE THREAD

**Issue by VenusMods** [rastapasta/pokemon-go-mitm#120]
So when getting protobuf on windows, I dont understand what it means when it says to put files in $PROTOBUF$/lib and stuff, since those arent even folders?

**Comment by BrunoGysin** [comment]
http://prntscr.com/c1pvm6

variable name:PROTOBUF
path: folder path dir


what you did to get build? I'm trying something hours but nothing
only thing that has these files are nothing:
'Libprotobuf.lib'
http://prntscr.com/c1pvzb

help me :S

**Comment by VenusMods** [comment]
Wait but it says but the include files in $(LIBPROTOBUF)/include so??? Also which lib folder do i put the libprotobuf.lib file in.

**Comment by BrunoGysin** [comment]
any folder

$(LIBPROTOBUF) It is a variable system
which should contain the path of the folder
Ex:
LIBPROTOBUF = C:\test\
and in folder:
C:\test\ 
It has 'include' folder and 'lib' folder.

**Comment by VenusMods** [comment]
@BrunoGysin So then you put the libprotobuf.lib in that lib foler, and all the include files in that folder?

**Comment by BrunoGysin** [comment]
create new folder Exemplo: 'Test', in 'Test' folder Create new folder with name 'lib', in 'lib' folder add 'libprotobuf.lib'. Back to 'Test' folder, copy 'include' folder and paste in 'Test' folder.

**Comment by VenusMods** [comment]
@BrunoGysin Ok thats what i did, but i still cant install node-protobuf

**Comment by roeifetaya** [comment]
me too

**Comment by rastapasta** [comment]
try to import the precompiled version of protobuf linked in #1 - or get a VM/vServer with Ubuntu to avoid the Windows pain. Cheers!
