### ISSUE TITLE
Can't install Node-Protobuf

### ISSUE THREAD

**Issue by VenusMods** [rastapasta/pokemon-go-mitm#122]
Keep getting this error:
C:\Users\Johnsons>npm install node-protobuf
|
> node-protobuf@1.3.3 install C:\Users\Johnsons\node_modules\node-protobuf
> node-gyp rebuild

C:\Users\Johnsons\node_modules\node-protobuf>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  init.cpp
  native.cpp
  parse.cpp
  serialize.cpp
C:\Users\Johnsons\Documents\Variables\include\google/protobuf/io/coded_stream.h(977): warning C4244: '=' : conversion f
rom '__int64' to 'int', possible loss of data (..\src\native.cpp) [C:\Users\Johnsons\node_modules\node-protobuf\build\p
rotobuf.vcxproj]
C:\Users\Johnsons\Documents\Variables\include\google/protobuf/io/coded_stream.h(977): warning C4244: '=' : conversion f
rom '__int64' to 'int', possible loss of data (..\src\parse.cpp) [C:\Users\Johnsons\node_modules\node-protobuf\build\pr
otobuf.vcxproj]
C:\Users\Johnsons\Documents\Variables\include\google/protobuf/io/coded_stream.h(977): warning C4244: '=' : conversion f
rom '__int64' to 'int', possible loss of data (..\src\init.cpp) [C:\Users\Johnsons\node_modules\node-protobuf\build\pro
tobuf.vcxproj]
C:\Users\Johnsons\Documents\Variables\include\google/protobuf/io/coded_stream.h(977): warning C4244: '=' : conversion f
rom '__int64' to 'int', possible loss of data (..\src\serialize.cpp) [C:\Users\Johnsons\node_modules\node-protobuf\buil
d\protobuf.vcxproj]
C:\Users\Johnsons\Documents\Variables\include\google/protobuf/io/coded_stream.h(1162): warning C4244: 'return' : conver
sion from '__int64' to 'int', possible loss of data (..\src\native.cpp) [C:\Users\Johnsons\node_modules\node-protobuf\b
uild\protobuf.vcxproj]
C:\Users\Johnsons\Documents\Variables\include\google/protobuf/io/coded_stream.h(1162): warning C4244: 'return' : conver
sion from '__int64' to 'int', possible loss of data (..\src\parse.cpp) [C:\Users\Johnsons\node_modules\node-protobuf\bu
ild\protobuf.vcxproj]
C:\Users\Johnsons\Documents\Variables\include\google/protobuf/io/coded_stream.h(1162): warning C4244: 'return' : conver
sion from '__int64' to 'int', possible loss of data (..\src\init.cpp) [C:\Users\Johnsons\node_modules\node-protobuf\bui
ld\protobuf.vcxproj]
C:\Users\Johnsons\Documents\Variables\include\google/protobuf/io/coded_stream.h(1162): warning C4244: 'return' : conver
sion from '__int64' to 'int', possible loss of data (..\src\serialize.cpp) [C:\Users\Johnsons\node_modules\node-protobu
f\build\protobuf.vcxproj]
C:\Users\Johnsons\Documents\Variables\include\google/protobuf/io/zero_copy_stream_impl_lite.h(51): fatal error C1083: C
annot open include file: 'google/protobuf/stubs/stl_util.h': No such file or directory (..\src\native.cpp) [C:\Users\Jo
hnsons\node_modules\node-protobuf\build\protobuf.vcxproj]
C:\Users\Johnsons\Documents\Variables\include\google/protobuf/io/zero_copy_stream_impl_lite.h(51): fatal error C1083: C
annot open include file: 'google/protobuf/stubs/stl_util.h': No such file or directory (..\src\parse.cpp) [C:\Users\Joh
nsons\node_modules\node-protobuf\build\protobuf.vcxproj]
C:\Users\Johnsons\Documents\Variables\include\google/protobuf/io/zero_copy_stream_impl_lite.h(51): fatal error C1083: C
annot open include file: 'google/protobuf/stubs/stl_util.h': No such file or directory (..\src\init.cpp) [C:\Users\John
sons\node_modules\node-protobuf\build\protobuf.vcxproj]
C:\Users\Johnsons\Documents\Variables\include\google/protobuf/io/zero_copy_stream_impl_lite.h(51): fatal error C1083: C
annot open include file: 'google/protobuf/stubs/stl_util.h': No such file or directory (..\src\serialize.cpp) [C:\Users
\Johnsons\node_modules\node-protobuf\build\protobuf.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Johnsons\node_modules\node-protobuf
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-protobuf"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-protobuf@1.3.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-protobuf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Johnsons\npm-debug.log

**Comment by yanniboi** [comment]
same errors on ubuntu 14.04

**Comment by rastapasta** [comment]
@VenusMods use the precompiled binaries from [here](https://github.com/rastapasta/pokemon-go-mitm/issues/1)
@yanniboi make sure to have the apt packages installed that are mentioned in the Readme
Cheers!
