### ISSUE TITLE
[HELP] I don't get objects of the pokestops

### ISSUE THREAD

**Issue by LoveOFF** [rastapasta/pokemon-go-mitm#124]
I just only can to change the image of the pokestop.

How do I get masterrball or inventory? please

thanks very much

**Comment by jmoriau** [comment]
You can only change the visual/names/items on your client, it's a cosmetic change, you'll never have a masterball using this.
Also issues are not a support forum please stop making these issues.

**Comment by cptcepk** [comment]
LoveOFF add me on skype
