### ISSUE TITLE
Pokemon Invisible, replace pokestop, visit pokestop, replace pokemon Not work ....

### ISSUE THREAD

**Issue by BrunoGysin** [rastapasta/pokemon-go-mitm#127]
I had big problems in windows, I downloaded a virtual machine and created a ubuntu.
In ubuntu work, i using 'coffee example.logTraffic.coffee' I see the logs, that means work.
In my android OR Nox (I Use Nox in windows) i Have APK 'proxydroid' Set proxy to my vitual machine and port 8081,  as I said earlier I see the logs..
installed [Xposed Framework](http://repo.xposed.info/module/de.robv.android.xposed.installer) and  [Pokemon Go Trust Certificate](http://repo.xposed.info/module/de.rastapasta.android.xposed.pokemongo)
![cbfeedc0ff4047819fba899aa2dd46a5](https://cloud.githubusercontent.com/assets/6241612/17442001/237e7d3e-5b0a-11e6-892b-77fe49fc834b.png)

the tutorial is:

Copy the generated .http-mitm-proxy/certs/ca.pem to your mobile
Add it to the "trusted certificates"

but I have not found any: .http-mitm-proxy/certs/ca.pem

whats wrong?

**Comment by jmoriau** [comment]
Right now most non-trivial request to go servers cannot be crafted. Visit pokestop will not work, same for always super throw etc.
The invisible pokemon issue has already been talked about in #75 please search a little before opening an issue.

Also issues **are not** a support forum stop so close this one and stop making these.

**Comment by BrunoGysin** [comment]
@jmoriau I search but with the name 'invisible' #75  Is [Ghost pokemon ](https://www.google.com.br/search?q=Ghost+pokemon&safe=off&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi3x4Oh1KrOAhURl5AKHbFWCj8Q_AUICCgB&biw=1271&bih=740)

I did not know it had already been reported in this topic.

**Comment by trisk** [comment]
The map showing empty cells is a general problem affecting all third-party applications that create or modify requests to the server right now. You cannot modify the data being sent by the real app currently.

**Comment by trisk** [comment]
The missing Pokémon models should load now that #75 is fixed, if this happens again let us know!
