### ISSUE TITLE
PTC Login not working

### ISSUE THREAD

**Issue by BRZ420** [rastapasta/pokemon-go-mitm#137]
It seems that PTC login is not done on every app start, instead it is cached for some time (several hours).

Sometimes, i get "Unable to log in" even on playing screen.

Restarting MITM proxy doesn't help.

The only way to fix issue is to disable proxy, restart app so that it can authorize with PTC, then enable proxy (after which restart works)

Also not sure if this is related to MITM proxy or xposed module

**Comment by rastapasta** [comment]
Hey @BRZ420, are you using ProxyDruid and have you installed the certificate? Cheers!

**Comment by BRZ420** [comment]
Yes, using ProxyDroid, and certificate is installed in system, as MITM obviously works if i get around initial PTC login.

**Comment by BRZ420** [comment]
Enabling debug, while pressing login repeatedly shows this in log:

```
[+++] Connect to  151.249.91.181:443
[-] HTTPS_CLIENT_ERROR on :
[+++] Connect to  151.249.91.181:443
[-] HTTPS_CLIENT_ERROR on :
[+++] Connect to  151.249.91.181:443
[-] HTTPS_CLIENT_ERROR on :
[+++] Connect to  151.249.91.181:443
[-] HTTPS_CLIENT_ERROR on :
[+++] Connect to  151.249.91.181:443
[-] HTTPS_CLIENT_ERROR on :
[+++] Connect to  151.249.91.181:443
[-] HTTPS_CLIENT_ERROR on :
[+++] Connect to  151.249.91.181:443
[-] HTTPS_CLIENT_ERROR on :
```

There are some other IP addresses with errors (google, unity), but they don't repeat on each login attempt

**Comment by BRZ420** [comment]
Seems to be related to #127 

Any chance on adding list of IP addresses to force domain?

**Comment by trisk** [comment]
@BRZ420 can you test the changes in #145 to see if that helps with your problem? That adds the PTC login server to the list to map to domains. Thanks!

**Comment by Toncek** [comment]
I had same problem after install new version of xposed-pokemon , so try to go for version 1.1 and than reboot your phone normal way (not just software restart from xposed )

**Comment by BRZ420** [comment]
Confirmed, working
