### ISSUE TITLE
Can´t understand this "CA" certificate I´m Noob

### ISSUE THREAD

**Issue by Go2750** [rastapasta/pokemon-go-mitm#138]
Run and quit coffee example.logTraffic.coffee to generate a CA certificate.

Copy the generated .http-mitm-proxy/certs/ca.pem to your mobile
Add it to the "trusted certificates"

I have this,but before I don´t now what to do 
http://goo.gl/yCzsd6

**Comment by darkoulis12** [comment]
run the coffee exmaple.blablabla :P
then in your folder press CTRL+H
to see hide files,then enter in mitm-proxy/certs  folder pick the ca.pem file,
and send it at your email...
go to your phone,open your mail and install the ca.pem in your phone
