### ISSUE TITLE
How change the Cp and IVs to my pokemons I need help

### ISSUE THREAD

**Issue by Go2750** [rastapasta/pokemon-go-mitm#140]
I put in the terminal this:

video: https://youtu.be/cii9XTO-AcA
```coffeescript
PokemonGoMITM = require './lib/pokemon-go-mitm'
server = new PokemonGoMITM port: 8081




And before I don´t now what put! :( 

I would like to improve my Pokemons just that and more XP
Example: I have a Dragonite with 2300 but I don´t know what put in the terminal to increase 3500 and IVs 100% :/

Someone who could put the code exactly increase my Dragonite  only that

please :c

**Comment by trisk** [comment]
A MITM proxy only changes what is displayed by your app. It doesn't change the actual values stored on the server, so changing IVs would be meaningless.

**Comment by Go2750** [comment]
But there is a file to change pokemon and there you can edit it to your liking

https://github.com/rastapasta/pokemon-go-mitm/blob/master/example.replacePokemons.coffee
