### ISSUE TITLE
Option for decode_raw

### ISSUE THREAD

**Issue by Lennix** [rastapasta/pokemon-go-mitm#144]
I was wondering if there's a way for pogo-mitm to decode_raw the packages to check if there are new fields which aren't described in the protos yet.

**Comment by trisk** [comment]
I think switching to `POGOProtos.parseWithUnknown` is sufficient to at least detect new fields, without side effects for existing scripts.

**Comment by rastapasta** [comment]
Thanks for taking care of that & implementing the change, @trisk !
