### ISSUE TITLE
Error when i type coffee example.logTraffic.coffee

### ISSUE THREAD

**Issue by Zhiend-E** [rastapasta/pokemon-go-mitm#147]
When i type the command pour generate a certificate i encoutered an error :

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8081
  at Object.exports._errnoException (util.js:1012:11)
  at exports._exceptionWithHostPort (util.js:1035:20)
  at Server._listen2 (net.js:1252:14)
  at listen (net.js:1288:10)
  at Server.listen (net.js:1384:5)
  at /home/xxxx/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/proxy.js:86:23
  at /home/xxxx/pokemon-go-mitm-node/node_modules/http-mitm-proxy/lib/ca.js:132:12
  at /home/xxxx/pokemon-go-mitm-node/node_modules/async/lib/async.js:726:13
  at /home/xxxx/pokemon-go-mitm-node/node_modules/async/lib/async.js:52:16
  at /home/xxxx/pokemon-go-mitm-node/node_modules/async/lib/async.js:269:32
  at /home/xxxx/pokemon-go-mitm-node/node_modules/async/lib/async.js:44:16
  at /home/xxxx/pokemon-go-mitm-node/node_modules/async/lib/async.js:723:17
  at /home/xxxx/pokemon-go-mitm-node/node_modules/async/lib/async.js:167:37
  at /home/xxxx/pokemon-go-mitm-node/node_modules/async/lib/async.js:726:13
  at /home/xxxx/pokemon-go-mitm-node/node_modules/async/lib/async.js:52:16
  at done (/home/xxxx/pokemon-go-mitm-node/node_modules/async/lib/async.js:246:17)
  at /home/xxxx/pokemon-go-mitm-node/node_modules/async/lib/async.js:44:16
  at /home/xxxx/pokemon-go-mitm-node/node_modules/async/lib/async.js:723:17
  at /home/xxxx/pokemon-go-mitm-node/node_modules/async/lib/async.js:167:37
  at FSReqWrap.oncomplete (fs.js:123:15)

I have nodejs v6.3.1 & npm v3.10.5

Thanks

**Comment by rastapasta** [comment]
You have a second proxy running on port 8081 somewhere in the background ;)
Stop it or change the port of this (new) proxy to another one. Cheers!
