### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by roeifetaya** [rastapasta/pokemon-go-mitm#148]
everytime i type in cmd "npm install" it gives me this problem and i have done all of the steps until this part!!

npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15)
npm WARN addRemoteGit  git+https://github.com/joeferner/node-http-mitm-proxy.git resetting remote C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-joeferner-node-http-mitm-proxy-git-d5a86359 because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:14:12)
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:69:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:90:16
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/joeferner/node-http-mitm-proxy.git C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-joeferner-node-http-mitm-proxy-git-d5a86359: undefined
npm ERR! git clone --template=C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/joeferner/node-http-mitm-proxy.git C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-joeferner-node-http-mitm-proxy-git-d5a86359: undefined
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\npm-debug.log

**Comment by roeifetaya** [comment]
i already compiled protobuf
pls help me!! i am trying to fix this problom for 6 days and still i didn't found a way to fix it!

**Comment by Toncek** [comment]
it looks like you dont have git installed , so try to install git properly and add "git" to your path

**Comment by roeifetaya** [comment]
how do i do it? pls ad me on skype: roei.fetaya

**Comment by Toncek** [comment]
type "how to install git on windows" and follow first link

**Comment by roeifetaya** [comment]
thx you so much you are awesome

**Comment by roeifetaya** [comment]
do i just download it and thats it? or do i need to do more things?

**Comment by roeifetaya** [comment]
pls just add me on skype if you have! (roei.fetaya)

**Comment by roeifetaya** [comment]
i installed it it did it but in the end it had a problom is it bad? (look at the end of the problom)

npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:323:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:492:12)
npm WARN addRemoteGit  git+https://github.com/joeferner/node-http-mitm-proxy.git resetting remote C:\Users\user\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-joeferner-node-http-mitm-proxy-git-d5a86359 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:323:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:492:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
[    ..............] | fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/upper-case    ..............] | fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/upper-case[    ..............] | fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/upper-case[    ..............] | fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/upper-case[    ..............] | fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/upper-case[    ..............] | fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/upper-case[    ..............] / fe
> node-protobuf@1.3.3 install C:\Users\user\node_modules\node-protobuf
> node-gyp rebuild


C:\Users\user\node_modules\node-protobuf>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\node_modules\node-protobuf
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
pokemon-go-mitm@1.7.0 C:\Users\user
+-- bluebird@3.4.1
+-- change-case@3.0.0
| +-- camel-case@3.0.0
| +-- constant-case@2.0.0
| +-- dot-case@2.1.0
| +-- header-case@1.0.0
| +-- is-lower-case@1.1.3
| +-- is-upper-case@1.1.2
| +-- lower-case@1.1.3
| +-- lower-case-first@1.0.2
| +-- no-case@2.3.0
| +-- param-case@2.1.0
| +-- pascal-case@2.0.0
| +-- path-case@2.1.0
| +-- sentence-case@2.1.0
| +-- snake-case@2.1.0
| +-- swap-case@1.1.2
| +-- title-case@2.1.0
| +-- upper-case@1.1.3
| `-- upper-case-first@1.1.2
+-- coffee-script@1.10.0
+-- geodesy@1.1.0
+-- http-mitm-proxy@0.5.1  (git+https://github.com/joeferner/node-http-mitm-proxy.git#a6f8469401616cec13c3f16f685021a33df7e0df)
| +-- async@1.5.2
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
| +-- node-forge@0.6.42
| +-- optimist@0.6.1
| | `-- wordwrap@0.0.3
| +-- semaphore@1.0.5
| `-- ws@1.1.1
|   +-- options@0.0.6
|   `-- ultron@1.0.2
+-- lodash@4.14.1
+-- moment@2.14.1
+-- request@2.74.0
| +-- aws-sign2@0.6.0
| +-- aws4@1.4.1
| +-- bl@1.1.2
| | `-- readable-stream@2.0.6
| |   +-- core-util-is@1.0.2
| |   +-- inherits@2.0.1
| |   +-- isarray@1.0.0
| |   +-- process-nextick-args@1.0.7
| |   +-- string_decoder@0.10.31
| |   `-- util-deprecate@1.0.2
| +-- caseless@0.11.0
| +-- combined-stream@1.0.5
| | `-- delayed-stream@1.0.0
| +-- extend@3.0.0
| +-- forever-agent@0.6.1
| +-- form-data@1.0.0-rc4
| +-- har-validator@2.0.6
| | +-- chalk@1.1.3
| | | +-- ansi-styles@2.2.1
| | | +-- escape-string-regexp@1.0.5
| | | +-- has-ansi@2.0.0
| | | | `-- ansi-regex@2.0.0
| | | +-- strip-ansi@3.0.1
| | | `-- supports-color@2.0.0
| | +-- commander@2.9.0
| | | `-- graceful-readlink@1.0.1
| | +-- is-my-json-valid@2.13.1
| | | +-- generate-function@2.0.0
| | | +-- generate-object-property@1.2.0
| | | | `-- is-property@1.0.2
| | | +-- jsonpointer@2.0.0
| | | `-- xtend@4.0.1
| | `-- pinkie-promise@2.0.1
| |   `-- pinkie@2.0.4
| +-- hawk@3.1.3
| | +-- boom@2.10.1
| | +-- cryptiles@2.0.5
| | +-- hoek@2.16.3
| | `-- sntp@1.0.9
| +-- http-signature@1.1.1
| | +-- assert-plus@0.2.0
| | +-- jsprim@1.3.0
| | | +-- extsprintf@1.0.2
| | | +-- json-schema@0.2.2
| | | `-- verror@1.3.6
| | `-- sshpk@1.9.2
| |   +-- asn1@0.2.3
| |   +-- assert-plus@1.0.0
| |   +-- dashdash@1.14.0
| |   | `-- assert-plus@1.0.0
| |   +-- ecc-jsbn@0.1.1
| |   +-- getpass@0.1.6
| |   | `-- assert-plus@1.0.0
| |   +-- jodid25519@1.0.2
| |   +-- jsbn@0.1.0
| |   `-- tweetnacl@0.13.3
| +-- is-typedarray@1.0.0
| +-- isstream@0.1.2
| +-- json-stringify-safe@5.0.1
| +-- mime-types@2.1.11
| | `-- mime-db@1.23.0
| +-- node-uuid@1.4.7
| +-- oauth-sign@0.8.2
| +-- qs@6.2.1
| +-- stringstream@0.0.5
| +-- tough-cookie@2.3.1
| `-- tunnel-agent@0.4.3
+-- request-promise@4.1.1
| +-- request-promise-core@1.1.1
| `-- stealthy-require@1.0.0
`-- simple-s2-node@0.0.1  (git+https://github.com/billyriantono/simple-s2-node.git#03b1aa9330688e273ef03b8989fe31addb0ad892)
  +-- bn@1.0.1
  `-- long@3.2.0

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-protobuf@1.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-protobuf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\npm-debug.log

**Comment by roeifetaya** [comment]
is it bad? or does it mean that it is working?

**Comment by rastapasta** [comment]
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

Please read your own logs 😄
