### ISSUE TITLE
i have problom with npm

### ISSUE THREAD

**Issue by roeifetaya** [rastapasta/pokemon-go-mitm#149]
> node-protobuf@1.3.3 install C:\Users\user\node_modules\node-protobuf
> node-gyp rebuild

C:\Users\user\node_modules\node-protobuf>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  init.cpp
  native.cpp
  parse.cpp
  serialize.cpp
c:\users\user\node_modules\node-protobuf\src\common.h(11): fatal error C1083: Cannot open include file: 'google/protobu
f/descriptor.h': No such file or directory (compiling source file ..\src\serialize.cpp) [C:\Users\user\node_modules\nod
e-protobuf\build\protobuf.vcxproj]
c:\users\user\node_modules\node-protobuf\src\common.h(11): fatal error C1083: Cannot open include file: 'google/protobu
f/descriptor.h': No such file or directory (compiling source file ..\src\parse.cpp) [C:\Users\user\node_modules\node-pr
otobuf\build\protobuf.vcxproj]
c:\users\user\node_modules\node-protobuf\src\common.h(11): fatal error C1083: Cannot open include file: 'google/protobu
f/descriptor.h': No such file or directory (compiling source file ..\src\init.cpp) [C:\Users\user\node_modules\node-pro
tobuf\build\protobuf.vcxproj]
c:\users\user\node_modules\node-protobuf\src\common.h(11): fatal error C1083: Cannot open include file: 'google/protobu
f/descriptor.h': No such file or directory (compiling source file ..\src\native.cpp) [C:\Users\user\node_modules\node-p
rotobuf\build\protobuf.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\node_modules\node-protobuf
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-protobuf@1.3.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-protobuf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\npm-debug.log

what do i do?

**Comment by roeifetaya** [comment]
i have done everything!! pls help and pls dont close this!

**Comment by jmoriau** [comment]
Issues are not a support forum, your previous issues got closed for the same reason, stop making these.

**Comment by roeifetaya** [comment]
this is a new issue and this tab called issues!

**Comment by jmoriau** [comment]
Issues are for real issues about the project not your specific setup.

**Comment by roeifetaya** [comment]
if you would help me insted of just telling me to close it it would be great!!!!!

**Comment by roeifetaya** [comment]
and it is a problom with the project i did the step but i get this error

**Comment by roeifetaya** [comment]
someone pls help!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by roeifetaya** [comment]
pls someone help!

**Comment by rastapasta** [comment]
please refrain from spamming. this is a dev project, not a support hotline.
all answers are already here, look around before ranting for help.
get a precompiled version of protobuf.
read here https://github.com/rastapasta/pokemon-go-mitm/issues/1

**Comment by roeifetaya** [comment]
i did it protobuf is not the problom it says that the problem is the npm

**Comment by roeifetaya** [comment]
and i am sorry for spamming pls add me on skype: roei.fetaya if you can and help me plss!

**Comment by rastapasta** [comment]
your node and npm versions are alright - its a compilation issue. its known that it's a pain in the booty to get it running on windows. either try the precompiled version of the protobuf lib or get a Ubuntu vServer or VM. barely anyone uses windows for this project, so very few people to ask. maybe ask in #1 - we as project maintainers can't help you.

**Comment by roeifetaya** [comment]
thx i did it!!!
