### ISSUE TITLE
Problem with proxy..

### ISSUE THREAD

**Issue by Zhiend-E** [rastapasta/pokemon-go-mitm#150]
HEllo, i have configure my phone like this : proxy set to manual, host is ip adress of my computer, port is 8081, BUT, when i run the game, it said me the server is over,try again later..

CAn you help me ?

**Comment by jmoriau** [comment]
what OS?
what distribution?
does the proxy run on your home computer or a server?
if it's on your home computer are you using a router?
if yes did you forward the port to your computer?
is your firewall on?
if yes is the port 8081 open?
are you on android?
are you on ios?
did you root and install the xposed module on android?
did you jailbreak and install the module on ios?
also note that until request signature is added you can't craft/modify any request you can only listen

good luck!

**Comment by Zhiend-E** [comment]
I have ubuntu on virtual machine, firewall is on, i think, but port 8081 is not open on my box, i've tried this, i have android whithout root, i use a pokemon go version whitout certificat pinning, thanks

**Comment by rastapasta** [comment]
make sure that your vm is configured to bridged network mode to let it get an own ip in your network

**Comment by Zhiend-E** [comment]
Oh ok, i change that

**Comment by jmoriau** [comment]
then after that you only need to forward the port on your router and open it on ubuntu if the firewall is enabled.

**Comment by Zhiend-E** [comment]
It's really frustrating, I enabled port 8081 on my router, I changed the virtual box in bridged mode for ubuntu, but it does it even connects to the network

**Comment by jmoriau** [comment]
` I enabled port 8081 on my router`
Did you `forward` it correctly to the vm's IP, also the how's the firewall on the VM?

**Comment by Zhiend-E** [comment]
Yes I configured port 8081 for vm, with the IP address thereof, but... i search for the firewall on the VM

**Comment by jmoriau** [comment]
http://manpages.ubuntu.com/manpages/wily/man8/ufw.8.html

**Comment by Zhiend-E** [comment]
Nice thanks you, the firewall is now activate, i will try for pokemon go now

**Comment by Zhiend-E** [comment]
I managed to run the bridge mode of the vm I opened port 8081 in the router stating clearly ubuntu, I have executed the command npm start, I activated the firewall, i've installed the certificate on my android phone, I have a version of pokemon go without pinning, I've configured the proxy on the smartphone, but its not working, should I forget something?

**Comment by jmoriau** [comment]
``` I activated the firewall,```

Did you open the port on the firewall ? By default they're all closed.

**Comment by Zhiend-E** [comment]
Oh maaaan, i have forget this, i have type : sudo ufw allow 8081, it's ok like this ?

**Comment by jmoriau** [comment]
yes

**Comment by Zhiend-E** [comment]
Ok last one, I managed to connect me, should I change the certificate if I change the script?
AND
Thanks for your help :)

**Comment by jmoriau** [comment]
awesome no you don't need to change the certificate.
