### ISSUE TITLE
help !

### ISSUE THREAD

**Issue by faloopa** [rastapasta/pokemon-go-mitm#151]
im very new to this stuff. i was wondering if anyone is willing to do a video tutorial on this because im more of a visual learner. thanks.

**Comment by jmoriau** [comment]
Hello,

No there won't be any video tutorial, this project is not meant to be used as-is, it is not a one-click install. Instead it provides the building blocks to write your own scripts. If you can't write javascript/coffeescript then I'm afraid you can't use this project.
