### ISSUE TITLE
what version of pokemon go is it working for?

### ISSUE THREAD

**Issue by roeifetaya** [rastapasta/pokemon-go-mitm#152]
i already set everything up but what version of pokemon go is it working for?

**Comment by rastapasta** [comment]
all of them, check the readme how to patch / used a patched version - Cheers!

**Comment by roeifetaya** [comment]
is it working for the latest version?

**Comment by rastapasta** [comment]
as long as they haven't update in the last 35 seconds: yes.

**Comment by roeifetaya** [comment]
thank you so much for helping me and for the help you did when i couldent compile it!!

**Comment by rastapasta** [comment]
:heart:

**Comment by roeifetaya** [comment]
last quastion where is the pre patched apk for android? can you pls give me a link?

**Comment by roeifetaya** [comment]
pls?

**Comment by rastapasta** [comment]
because of the "pls" 😄 
it's linked in the README as well 🐼 
https://goo.gl/XFzgrX

**Comment by roeifetaya** [comment]
thx you so much i have installed it and i tryied generating the .http-mitm-proxy/certs/ca.pem
but i got this: > pokemon-go-mitm@1.7.0 start C:\Users\user\Desktop\LIBPROTOBUF\pokemon-go-mitm-master
> coffee example.logTraffic.coffee

[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device
 
whre is the .http-mitm-proxy/certs/ca.pem

**Comment by roeifetaya** [comment]
never mind found it!
