### ISSUE TITLE
Add the certificate to the "trusted certificates" of your mobile where is it?

### ISSUE THREAD

**Issue by roeifetaya** [rastapasta/pokemon-go-mitm#153]
Add the certificate to the "trusted certificates" of your mobile i cant find where to find it for android i searched google but nothing pls help!!

**Comment by roeifetaya** [comment]
i know it is not support forum just pls tell me where is it for android! pls!!

**Comment by rastapasta** [comment]
http://bit.ly/2b9ANCH
sorry man, but that's the last question of yours i will answer.
all of them could have been solved by reading the README or simply enter it to google.
