### ISSUE TITLE
[Quastion] did somebody successfully made a legendary script?

### ISSUE THREAD

**Issue by roeifetaya** [rastapasta/pokemon-go-mitm#157]
did somebody successfully a legendary script that spawns a legendary?
I tried but it is not working! I want to see someone else script just to see what I did wrong!!

**Comment by roeifetaya** [comment]
or a fixed and working version of this: server = new PokemonGoMITM port: 8081
# Parse the wild pokemons nearby
.addResponseHandler "GetMapObjects", (data) ->
return false if not data.map_cells.length

for cell in data.map_cells
  if cell.catchable_pokemons.length > 0
    first_pokemon = cell.catchable_pokemons[0]
    cell.catchable_pokemons[0].pokemon_id = 'MEWTWO'
    console.log('Altered cell.catchable_pokemons')
    console.log(cell.catchable_pokemons[0])
    for nearby in cell.nearby_pokemons
      if nearby.encounter_id == first_pokemon.encounter_id
        nearby.pokemon_id = 'MEWTWO'
        console.log('Altered Neraby pokemons')
        console.log(nearby)
        console.log('Wild pokemon: ')
        cell.wild_pokemons[0].pokemon_data.pokemon_id = 'MEWTWO'
        console.log(cell.wild_pokemons[0])
data`

**Comment by caspaas** [comment]
Im working on the same thing and cant get it too work :/

**Comment by Poootaatoooo** [comment]
you have to have an encounter of any pokemon for it to show the mewtwo

**Comment by roeifetaya** [comment]
no listen poootaatoooo the script is crashing and i don't know why!

**Comment by Poootaatoooo** [comment]
here's a script that empties your pokedex and spawns mewtwos:

PokemonGoMITM = require './lib/pokemon-go-mitm'
server = new PokemonGoMITM port: 8081
 
 
coughtIDs = []
server.addResponseHandler "CatchPokemon", (data) ->
    if "status" of data
        if data.status == "CATCH_SUCCESS"
            coughtIDs.push data.captured_pokemon_id
            data.capture_award.activity_type[1] = "ACTIVITY_POKEDEX_ENTRY_NEW"
            data.capture_award.xp = "0": 1000000000000, "1": 100000000000
            data.capture_award.candy = "0": 3, "1": 0
            data.capture_award.stardust = "0": 100, "1": 0
            console.log("dataflata")
            console.log(JSON.stringify(data,null,4))
    data
server.addResponseHandler "GetInventory", (data) ->
    if "success" of data
        if data.success
            for item in data.inventory_delta.inventory_items
                if "pokemon_data" of item.inventory_item_data
                    if item.inventory_item_data.pokemon_data.id in coughtIDs
                        item.inventory_item_data.pokemon_data.pokemon_id = "MEWTWO"
                        item.inventory_item_data.pokemon_data.cp = 3249
                        item.inventory_item_data.pokemon_data.stamina = 221
                        item.inventory_item_data.pokemon_data.stamina_max = 221
                        item.inventory_item_data.pokemon_data.weight_kg = 122.28
                        item.inventory_item_data.pokemon_data.height_m = 2.07
                        item.inventory_item_data.pokemon_data.move_1 = "PSYCHIC"
                        item.inventory_item_data.pokemon_data.move_2 = "PSYSTRIKE"
                        item.inventory_item_data.pokemon_data.individual_attack = 30
                        item.inventory_item_data.pokemon_data.individual_defense = 20
                        item.inventory_item_data.pokemon_data.individual_stamina = 15
                if "pokedex_entry" of item.inventory_item_data
                    item.inventory_item_data.pokedex_entry.times_encountered = 1
                    item.inventory_item_data.pokedex_entry.times_captured = 1
                    item.inventory_item_data.pokedex_entry.pokemon_id = "MEWTWO"
                if "candy" of item.inventory_item_data
                    item.inventory_item_data.candy.family_id = "MEWTWO"
                    item.inventory_item_data.candy.candy = 3
    data
 
server.addResponseHandler "GetMapObjects", (data) ->
    if "map_cells" of data
        cal = new Date()
        now = cal.getTime()
        for cell in data.map_cells
            for mon in cell.catchable_pokemons
                mon.pokemon_id = "MEWTWO"
               
            for mon in cell.wild_pokemons
                mon.pokemon_data.pokemon_id = "MEWTWO"
    data
server.addResponseHandler "DiskEncounter", (data) ->
        data.capture_probability.capture_probability = [1, 1, 1 ]
        data

server.addResponseHandler "Encounter", (data) ->
    if "status" of data
        if data.status == "ENCOUNTER_SUCCESS"
            data.wild_pokemon.pokemon_data.pokemon_id = "MEWTWO"
            data.wild_pokemon.pokemon_data.cp = 8000
            data.wild_pokemon.pokemon_data.weight_kg = 122
            data.wild_pokemon.pokemon_data.height_m = 2
            data.capture_probability.capture_probability['0'] = 0.0
            data.capture_probability.capture_probability['1'] = 0.0
            data.capture_probability.capture_probability['2'] = 0.1
 
    data
ignore = ['GetInventory', 'GetMapObjects', 'CatchPokemon', 'Encounter']
 
server.addRequestHandler "*", (data, action) ->
        console.log "[<-] Request for #{action} ", data, "\n" unless not (action in ignore)
        data
 
server.addResponseHandler "*", (data, action) ->
        console.log "[->] Response for #{action} ", JSON.stringify(data, null, 4), "\n" unless not (action in ignore)
        data


maybe you can learn from it?

**Comment by roeifetaya** [comment]
I have this one already but it doesn't spawn mewtwo it will like the other pokemons until you will capture him and than when it will register to the pokedex it will turn into mewtwo I meant a script that spawn mewtwo with his model so you could capture him!

**Comment by Poootaatoooo** [comment]
huh... for me it spawns 3 mewtwos and then you can capture them, I'm not really good at scripting and that's not even my script so i don't know

**Comment by roeifetaya** [comment]
And it doesn't give me mewtwo candy's so I can't power him up!

**Comment by roeifetaya** [comment]
To get an encounter I have to still be connected to wifi so I can't walk away from home how did you managed to get an encounter?

**Comment by roeifetaya** [comment]
Maybe I didn't saw is model because to get an encounter I had to use the item that spawns pokemons next to you!

**Comment by Poootaatoooo** [comment]
i port forwarded my local ip in my router to 8081 so i can access it with my public ip on my mobile data

**Comment by roeifetaya** [comment]
how did you do it? did you used android?

**Comment by Poootaatoooo** [comment]
yes

**Comment by roeifetaya** [comment]
can you teach me pls?

**Comment by roeifetaya** [comment]
?

**Comment by Poootaatoooo** [comment]
what router do you have?

**Comment by roeifetaya** [comment]
d-link

**Comment by Poootaatoooo** [comment]
go to http://192.168.0.1 and login, the default username is "admin" and the password is nothing

**Comment by roeifetaya** [comment]
it doesnt work do i need to enter my ip?

**Comment by Poootaatoooo** [comment]
do you know the exact model of your router?

**Comment by roeifetaya** [comment]
no

**Comment by Poootaatoooo** [comment]
try 192.168.1.1

**Comment by roeifetaya** [comment]
i enterd my defult ip and it worked!

**Comment by roeifetaya** [comment]
what do i do next?

**Comment by Poootaatoooo** [comment]
can you screenshot the page?

**Comment by roeifetaya** [comment]
i aam in the advance tab and i see an port forward option

**Comment by roeifetaya** [comment]
do you have skype? so i could screenshare?

**Comment by Poootaatoooo** [comment]
one second

**Comment by Poootaatoooo** [comment]
skype: potato.paradox

**Comment by roeifetaya** [comment]
i snet you a messege

**Comment by roeifetaya** [comment]
i have a problom with pokemon go it's says failed to detect location forever it doesnt matter what i do! help!!
