### ISSUE TITLE
Can't connect with proxydroid

### ISSUE THREAD

**Issue by Poootaatoooo** [rastapasta/pokemon-go-mitm#158]
As the title says, do I have to configure it a certain way? I prefer using proxydroid over the built in system settings so if someone could help me, that'd be great, thanks!

**Comment by rastapasta** [comment]
All good with proxydruid - if you are using PTC, just make sure you login first, quit the app, activate proxydruid and finally start the app again. Cheers!

**Comment by Poootaatoooo** [comment]
just realized the proxy was the problem, the port 8081 wasn't even open :P
