### ISSUE TITLE
Certificate

### ISSUE THREAD

**Issue by Fechinator** [rastapasta/pokemon-go-mitm#160]
Hey,

if i run my coffeescript there aren't any errors, but i can't find this folder ".http-mitm-proxy/certs/ca.pem".
It's not even shown when unhiding hidden folders.

The example scripts don't generate a certificate, too.

Do you have any idea? Thanks in advance.

**Comment by rastapasta** [comment]
Please take a look at the readme, there are instructions given for this situation - Cheers!
