### ISSUE TITLE
using it with mobile data? [quastion]

### ISSUE THREAD

**Issue by roeifetaya** [rastapasta/pokemon-go-mitm#166]
did somebody found a way to use this with mobile data with android?
i searched how to do it for a wail but i found nothing!

**Comment by jmoriau** [comment]
*sigh*

**Comment by roeifetaya** [comment]
its a quastion!

**Comment by jmoriau** [comment]
I would close it but you're just gonna create a new one anyway.

**Comment by roeifetaya** [comment]
no it is a quastion not a problom
pls no

**Comment by roeifetaya** [comment]
i just wanted to ask if someone succeded doing it

**Comment by jmoriau** [comment]
Can't you use Google like everyone else? Also do you not care that we've told countless times this is not a support Forum? It's up to you fix any problem NOT related to the project itself. Please stop opening new issues every time a thought crosses your mind. Learn to think and search yourself!

This is the absolute last time you'll get an answer to these kind of questions next time you can expect your non-issue to be closed without a comment.

Now let me google your non-issue for you: http://lmgtfy.com/?q=how+to+use+a+proxy+with+cellular+data+android

**Comment by roeifetaya** [comment]
first of all i know it is not a support forum i was asking a quastion i didnt need help!
and second of all i tried googling it nothing worked for me!

**Comment by jmoriau** [comment]
Yes and it still had absolutely nothing to do with the project itself.
