### ISSUE TITLE
RPI Certificate creation

### ISSUE THREAD

**Issue by Atrion** [rastapasta/pokemon-go-mitm#167]
`openssl genrsa -out .http-mitm-proxy/keys/ca.private.key 2048
openssl rsa -in .http-mitm-proxy/keys/ca.private.key -pubout > .http-mitm-proxy/keys/ca.public.key
openssl req -x509 -new -nodes -key .http-mitm-proxy/keys/ca.private.key -days 1024 -out .http-mitm-proxy/certs/ca.pem -subj "/C=US/ST=Utah/L=Provo/O=PokemonCA/CN=example.com"`

The First Line (When run with sudo) works fine.
The Second command says Permission denied (With and without sudo)
Havent gotten to the 3rd line yet, but also what is the last bit of the line suppsed to be changed to. I'm from PEI canada so would it be C=Can/ST=PEI/ what do the last 3 get changed to?

**Comment by trisk** [comment]
You messed up the ownership of the files. Your shell can't redirect to files owned by root. `chown` everything back to your user and don't use `sudo` for no reason in the future.
