### ISSUE TITLE
Problem setting up proxy

### ISSUE THREAD

**Issue by JacopoD** [rastapasta/pokemon-go-mitm#168]
Hi, i am new here i am having some issues setting up the proxy correctly. After generating manually the certificate i transferred it to my phone and i installed it and left all the settings untouched ( Name: ca VPN/Apps ) than i went to wi-fi settings and i followed the guide that @rastapasta linked. Proxy Host Name: what should i write here? I tried with my ip but it doesn't work. Proxy Port: 8081. with my ip and the port mentioned before i can't get it working 

ubuntu@ubuntu-virtual-machine:~$ cd pokemon-go-mitm-node/
ubuntu@ubuntu-virtual-machine:~/pokemon-go-mitm-node$ npm start

> pokemon-go-mitm@1.7.0 start /home/ubuntu/pokemon-go-mitm-node
> coffee example.logTraffic.coffee

[+++] PokemonGo MITM Proxy listening on 8081
[!] Make sure to have the CA cert .http-mitm-proxy/certs/ca.pem installed on your device

Maybe the problem is that i am on a Ubuntu VMware

**Comment by jmoriau** [comment]
see #150

**Comment by JacopoD** [comment]
Thanks i will let you know if it works!
