### ISSUE TITLE
A Requast For An Example 

### ISSUE THREAD

**Issue by AlexTheCoder007** [rastapasta/pokemon-go-mitm#169]
can we have an example of an evolution changer?
i have bieng  trying to make one for some time and it just doesn't work!

**Comment by jmoriau** [comment]
Hi,

Is it you @thestupidhackerderp323 (or whatever your nickname was before you changed roef-something) ?
If it's you, you've chosen the silliest nickname ever to fool us :joy: I'm actually 98% sure it's you!
Anyway what exactly did you mean by "evolution changer" also you say "i have bieng trying to make one for some time and it just doesn't work!"
Can you show us what you tried and doesn't work?
And when I say "what have you tried" I'm not expecting a 5 words sentence but the actual code you wrote yourself and the logic behind it. See [what-have-you-tried](http://mattgemmell.com/what-have-you-tried/).

**Comment by AlexTheCoder007** [comment]
wtf are you talking about?

**Comment by jmoriau** [comment]
You way of writing is extremely similar to #149 and many others from the same person.

**Comment by AlexTheCoder007** [comment]
who is this?

**Comment by AlexTheCoder007** [comment]
and i have bieng tring to do this but i dont know how to write it! do you have any advice?

**Comment by AlexTheCoder007** [comment]
isnted of compering me to some random dude!

**Comment by AlexTheCoder007** [comment]
insted*

**Comment by AlexTheCoder007** [comment]
i have succesfuly created a scrip that spawns pokemons but i dont know how to write one that changes the evoulotion!

**Comment by jmoriau** [comment]
`i dont know how to write it`

*sigh* Now I'm 99.9% sure it's you. Anyway even if it's not you, I'll say it again, the issues are for problem with the project. This not a problem with the project. A request for help to write an example even though not technically an issue could be accepted but you at least need to know how to write basic javascript/coffeescript. What *exactly*, *specifically* do you need help with?

**Comment by AlexTheCoder007** [comment]
i need an help for writing a pokemon evoulotion changer that changes that when i evolve a pokemon it will change it's id into Mew or any other pokemon
and i know how to write scripts

**Comment by jmoriau** [comment]
Then just run the logger example, evolve a pokemon, search through the logs and you'll see the relevant calls to intercept and modify.

**Comment by AlexTheCoder007** [comment]
ok thank you
