### ISSUE TITLE
reading the readme helps

### ISSUE THREAD

**Issue by MarkHuangZ** [rastapasta/pokemon-go-mitm#170]
![Linux Error](https://cloud.githubusercontent.com/assets/10660034/17591150/d7b6d414-5faa-11e6-948b-9d0d71346545.png)
[Windows Bug message.txt](https://github.com/rastapasta/pokemon-go-mitm/files/413377/New.Text.Document.txt)

[npm-debug.txt](https://github.com/rastapasta/pokemon-go-mitm/files/413394/npm-debug.txt)

Could you tell me which part i did wrong?

**Comment by jmoriau** [comment]
Works fine on ubuntu, did you do all the steps in the README?

**Comment by MarkHuangZ** [comment]
I believe so. I uploaded the error log here. It appears the same error message when I run it in Windows.

From Mark's IPhone.

**Comment by rastapasta** [comment]
from the readme:
**apt-get install libprotobuf-dev**
