### ISSUE TITLE
pokemon-go-mitm-node Configure Error

### ISSUE THREAD

**Issue by EtriusLeoVinci** [rastapasta/pokemon-go-mitm#171]
Your environment has been set up for using Node.js 4.4.7 (x64) and npm.

C:\Users\Matt>cd clone
The system cannot find the path specified.

C:\Users\Matt>cd desktop

C:\Users\Matt\Desktop>cd clone

C:\Users\Matt\Desktop\Clone>git clone https://github.com/rastapasta/pokemon-go-mitm-node.git && cd pokemon-go-mitm-node
Cloning into 'pokemon-go-mitm-node'...
remote: Counting objects: 643, done.
remote: Compressing objects: 100% (70/70), done.
emote: Total 643 (delta 36), reused 0 (delta 0), pack-reused 573
Receiving objects: 100% (643/643), 141.18 KiB | 0 bytes/s, done.

Resolving deltas: 100% (343/343), done.
Checking connectivity... done.

C:\Users\Matt\Desktop\Clone\pokemon-go-mitm-node>npm install
|
> node-protobuf@1.3.3 install C:\Users\Matt\Desktop\Clone\pokemon-go-mitm-node\node_modules\pokemongo-protobuf\node_modules\node-protobuf
> node-gyp rebuild

C:\Users\Matt\Desktop\Clone\pokemon-go-mitm-node\node_modules\pokemongo-protobuf\node_modules\node-protobuf>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Matt\Desktop\Clone\pokemon-go-mitm-node\node_modules\pokemongo-protobuf\node_modules\node-protobuf
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-protobuf@1.3.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-protobuf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Matt\Desktop\Clone\pokemon-go-mitm-node\npm-debug.log

C:\Users\Matt\Desktop\Clone\pokemon-go-mitm-node>

this is what i get when i clone the file in the Node.js CMD, it clones it fine (assuming it does.) with no problems, and when i do "C:\Users\Matt\Desktop\Clone\pokemon-go-mitm-node>npm install" i get the following output above. am i missing something? thank you for any help!

**Comment by cygnull** [comment]
Make sure you get protobuf... I had the same issues (granted I used a machine running linux so it was much easier) but mine was an old version of node.js.. then once I updated I had the error you're getting..
you need to hard compile [protobuf for a Windows enviroment](https://github.com/fuwaneko/node-protobuf#windows) .. or run a VM with a Linux Distro

**Comment by jmoriau** [comment]
There are countless issues about this please at least *try* to search before making a new issue.
