### ISSUE TITLE
Any Ideas On How To Set It Up With Mobile Deta On Android? [Quastion]

### ISSUE THREAD

**Issue by AlexTheCoder007** [rastapasta/pokemon-go-mitm#173]
i have bieng searching and nothing worked for me! 
i have tryed Proxydroid changing the APN and more stuff but it none of tham worked any ideas on what to do?
(this will be my last issue so pls dont close it by saying it is not a support forum i am just asking for advice!!)

**Comment by AlexTheCoder007** [comment]
i just need an advice

**Comment by jmoriau** [comment]
Also you're not fooling anyone by making a new account.
