### ISSUE TITLE
Help. Problem spawning snorlax

### ISSUE THREAD

**Issue by JacopoD** [rastapasta/pokemon-go-mitm#178]
I edited a code that i found to spawn mewtwo to make it spawn a snorlax when i run the .coffee i get this in response

-iMac:pokemon-go-mitm-node JDV$ coffee snorlax.coffee
/Users/JDV/pokemon-go-mitm-node/snorlax.coffee:46
              item.inventory_item_data.pokemon_data.pokemon_id = “SNORLAX”;
                                                                 ^
SyntaxError: Unexpected token ILLEGAL
  at Object.exports.runInThisContext (vm.js:76:16)
  at Module._compile (module.js:513:28)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.runMain (module.js:575:10)
  at run (bootstrap_node.js:352:7)
  at startup (bootstrap_node.js:144:9)
  at bootstrap_node.js:467:3

The code:

PokemonGoMITM = require './lib/pokemon-go-mitm'
server = new PokemonGoMITM port: 8081

coughtIDs = []
server.addResponseHandler "CatchPokemon", (data) ->
    if "status" of data
        if data.status == "CATCH_SUCCESS"
            coughtIDs.push data.captured_pokemon_id
            data.capture_award.activity_type[1] = "ACTIVITY_POKEDEX_ENTRY_NEW"
            data.capture_award.xp = "0": 100, "1": 500
            data.capture_award.candy = "0": 3, "1": 0
            data.capture_award.stardust = "0": 100, "1": 0
            console.log("dataflata")
            console.log(JSON.stringify(data,null,4))
    data
server.addResponseHandler "GetInventory", (data) ->
    if "success" of data
        if data.success
            for item in data.inventory_delta.inventory_items
                if "pokemon_data" of item.inventory_item_data
                    if item.inventory_item_data.pokemon_data.id in coughtIDs
                        item.inventory_item_data.pokemon_data.pokemon_id = “SNORLAX”
                        item.inventory_item_data.pokemon_data.cp = 8912
                        item.inventory_item_data.pokemon_data.stamina = 320
                        item.inventory_item_data.pokemon_data.stamina_max = 320
                        item.inventory_item_data.pokemon_data.weight_kg = 460.00
                        item.inventory_item_data.pokemon_data.height_m = 2.11
                        item.inventory_item_data.pokemon_data.move_1 = "PSYCHIC"
                        item.inventory_item_data.pokemon_data.move_2 = “NORMAL”
                        item.inventory_item_data.pokemon_data.individual_attack = 180
                        item.inventory_item_data.pokemon_data.individual_defense = 180
                        item.inventory_item_data.pokemon_data.individual_stamina = 320
                if "pokedex_entry" of item.inventory_item_data
                    item.inventory_item_data.pokedex_entry.times_encountered = 1
                    item.inventory_item_data.pokedex_entry.times_captured = 1
                    item.inventory_item_data.pokedex_entry.pokemon_id = “SNORLAX”
                if "candy" of item.inventory_item_data
                    item.inventory_item_data.candy.family_id = “SNORLAX”
                    item.inventory_item_data.candy.candy = 3
    data

server.addResponseHandler "GetMapObjects", (data) ->
    if "map_cells" of data
        cal = new Date()
        now = cal.getTime()
        for cell in data.map_cells
            for mon in cell.catchable_pokemons
                mon.pokemon_id = “SNORLAX”
                
            for mon in cell.wild_pokemons
                mon.pokemon_data.pokemon_id = “SNORLAX”
    data
server.addResponseHandler "Encounter", (data) ->
    if "status" of data
        if data.status == "ENCOUNTER_SUCCESS"
            data.wild_pokemon.pokemon_data.pokemon_id = “SNORLAX”
            data.wild_pokemon.pokemon_data.cp = 8000
            data.wild_pokemon.pokemon_data.weight_kg = 460
            data.wild_pokemon.pokemon_data.height_m = 2
            data.capture_probability.capture_probability['0'] = 0.0
            data.capture_probability.capture_probability['1'] = 0.0
            data.capture_probability.capture_probability['2'] = 0.1

    data

ignore = ['GetInventory', 'GetMapObjects', 'CatchPokemon', 'Encounter']

server.addRequestHandler "*", (data, action) ->
		console.log "[<-] Request for #{action} ", data, "\n" unless not (action in ignore)
		data

server.addResponseHandler "*", (data, action) ->
		console.log "[->] Response for #{action} ", JSON.stringify(data, null, 4), "\n" unless not (action in ignore)
		data

**Comment by jmoriau** [comment]
Just making sure but, are you aware that it is purely cosmetic **and** temporary? You won't get a real snorlax, in fact it will only change what is displayed on the app for this session and while you're connected to the proxy. 
As soon as you restart the app this is all gone. And eveb if you were to battle with this snorlax it would do the damage of the real pokemon you caught not the snorlax and everyone else would see the real pokemon not the snorlax.
Maybe I don't get the appeal of doing this but it seems so useless that I wonder why you're attempting to do something like this.
Finally coffeescript relies on the indentation of the code, it's very hard to read it like this. You should edit it to show the real indentation and maybe put it in a block with syntax higlighting.

**Comment by JacopoD** [comment]
Thanks for the help but is there any way to get them permanently?

**Comment by jmoriau** [comment]
Of course not, you're not even getting them, you're just tricking the client to render another model (the snorlax model) instead of the real one. It's purely cosmetic and therefore pointless.

**Comment by JacopoD** [comment]
Ok that's sad... Last question what is actually permanent ?

**Comment by jmoriau** [comment]
Absolutely nothing.

**Comment by JacopoD** [comment]
lol... thank you for the help
