### ISSUE TITLE
Pokemon Gym Battles?

### ISSUE THREAD

**Issue by PokeWoke** [rastapasta/pokemon-go-mitm#179]
I was wondering if the Pokemon you "hack" in can fight in Gyms. Like it was demonstrated by this guy: https://www.youtube.com/watch?v=Go__iSq_6cg I was wondering how you could do that. And I was also wondering how you can have multiple legendaries at once, for me I can only spawn 1 at a time.

**Comment by jmoriau** [comment]
Please see #178 then the comments on this video will make sense. (Hint: it's only a cosmetic change, he tricked the client into rendering models of other pokemons, but the game still considered them as they were before the cosmetic trick, also only the owner can see the changes, everyone else will see the regular pokemon)
