### ISSUE TITLE
map-based web client

### ISSUE THREAD

**Issue by AVVS** [rastapasta/pokemon-go-mitm#18]
I've been working on this for myself and use it currently with iOS / xcode GPS spoof, but it's quite boring and frustrating to have the app fail. That being said I think it would be a cool thing to build given that the API is somewhat open and we have more or less accurate mappings at this point.

I can help build the client if you guys can help with the API part. 

Roadmap is the following:

### Web client

- [x] google map with current location
- [x] walk around using w,a,s,d or up,down,left,right arrow
- [x] walk to a waypoint with a certain speed
- [x] walk through multiple waypoints
- [x] remove waypoints
- [x] pause movement
- [ ] display pokemons on the map
- [ ] engage in battles with pokemon
- [ ] look through inventory / interact with items
- [ ] hatch eggs
- [ ] evolve / release / power up pokemons

### API + MITM proxy

- [ ] login endpoint: far down the road, but assuming that we have a remote web-service running - this should generate ip/port for web & proxy and allow downloading CA cert directly to the phone
- [ ] moveTo: accepts lat/lon waypoint and starts moving towards in a human-like fashion
- [ ] pokemon location: pushes pokemon locations from server to client, using websocket or similar. Basically this is to show whats around you, ie navigation hub
- [ ] capture pokemon: based on data from previous endpoint engages in pokemon capturing, possibly settings restrictions on what items are allowed to be used
- [ ] ... etc. Some utility functions for farming pokestops, doing specific walking (spiral movement, for instance, and so on)

**Comment by rubenvereecken** [comment]
For future generations reading this, the conversation has moved to Slack and the topic moved to [Pokemon Go Enhanced](https://github.com/PokemonGo-Enhanced). Me and @AVVS saw the benefit in working together and will be working on something similar to what is described over there.
