### ISSUE TITLE
Can't connect from proxy to pogo servers..

### ISSUE THREAD

**Issue by cygnull** [rastapasta/pokemon-go-mitm#180]
I'm running the proxy on a laptop w/Kali-Rolling 2016.1, I can connect the Nexus 5x to the Proxy, but when starting the game, It starts loading then 

> "Failed  to get game data from servers."  

I can't figure out what I'm doing wrong =\

**Comment by rastapasta** [comment]
Are u using ProxyDruid or direct proxy setup in the wifi connection? Cheers!

**Comment by cygnull** [comment]
Direct proxy setup in WiFi settings.. I'll try proxydruid and see if that makes a difference

**Comment by BRZ420** [comment]
Did you install certificate? It should start with Node...
