### ISSUE TITLE
Change display username ?

### ISSUE THREAD

**Issue by maestrococ** [rastapasta/pokemon-go-mitm#183]
Hello, 
Who have a custom .coffee to change the display username ???

Thanks

**Comment by rastapasta** [comment]
just addResponseHandler to [GetPlayer](https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Networking/Responses/GetPlayerResponse.proto) and set data.[player_data](https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Data/PlayerData.proto).username = 'maestrococ'
