### ISSUE TITLE
can't decode locale from DownloadRemoteConfigVersion

### ISSUE THREAD

**Issue by FabryB** [rastapasta/pokemon-go-mitm#184]
I am trying to log `DownloadRemoteConfigVersion` but I always get:
`[<-] Request for DownloadRemoteConfigVersion  { platform: 'ANDROID', app_version: 3300, '$unknownFields': [] } ` no matter what I do.
I even tried to manually compile POGOprots and replace protocolo data, no luck.

Some help, please ?

**Comment by rastapasta** [comment]
please be more specific in your question - the log entry you posted is already the request's content. what else do you want to log? Cheers!

**Comment by FabryB** [comment]
According to this:
https://github.com/AeonLucid/POGOProtos/blob/master/src/POGOProtos/Networking/Requests/Messages/DownloadRemoteConfigVersionMessage.proto

I should have 5 parameters in the Request:
`message DownloadRemoteConfigVersionMessage {
	.POGOProtos.Enums.Platform platform = 1;
	string device_manufacturer = 2;
	string device_model = 3;
	string locale = 4;
	uint32 app_version = 5;
}`
but only two get decoded, I would like to see the other 3.

**Comment by rastapasta** [comment]
Thats neither an issue with the mitm, nor with the POGOProtos - if you can't see them in the dump, they are basically not set. Not all fields defined in the protocol are used on all devices or versions. Cheers!

**Comment by FabryB** [comment]
Thank you.
Is there an option somewhere to dump the empty fields?
I'd like more to see device_manufacturer = null, device_model = null and locale = null than not seeing them at all

**Comment by rastapasta** [comment]
Hummm, looked into it, the current protobuf library we're using here doesn't support that directly. There's a long going task to port this to protobufjs, a contributor is about to do that soon in his free time - this would allow pragmatic access to the schema fields, which in return would allow detect unset fields and set them to null. Stay tuned ;)
