### ISSUE TITLE
Only get GetPlayer request from logTraffic example

### ISSUE THREAD

**Issue by cryptax** [rastapasta/pokemon-go-mitm#186]
Hi,

I run the example.logTraffic.coffee script. I only get GetPlayer requests. Is that normal? I guess not... any idea why or how to debug?
The game go through the signin page, and then appears to be searching for something. I do not get to the map screen.

```
[+++] PokemonGo MITM [++++]
[+] Virtual endpoint listening on 8082
[!] -> ENDPOINT USAGE: configure 'custom endpoint' in pokemon-go-xposed
[+] Proxy listening on 8081
[!] -> PROXY USAGE: make sure to have .http-mitm-proxy/certs/ca.pem installed on your device
[<-] Request for GetPlayer { app_version: '0.31.0', '$unknownFields': []}
```

Note: 
- I do not have pokemon-go-xposed installed: I am using one of the modified apk with cert pinning disabled. This is indeed a version 0.31.0.
- My CA cert is installed on the device
- I have no GPS signal where I am, but I guess I should still have other requests showing if not the whole game running correctly.

**Comment by trisk** [comment]
Perhaps the current proto spec for the response envelope can no longer parse response envelopes sent to 0.31.0 clients. Try this script to show additional info:
```javascript
PokemonGoMITM = require './lib/pokemon-go-mitm'
server = new PokemonGoMITM port: 8081, debug: true
```

**Comment by trisk** [comment]
This looks a lot like the virtual endpoint gzip bug I just fixed; it broke response parsing (failed to detect gzipped responses). The standard proxy shouldn't have been affected  though.

**Comment by cryptax** [comment]
Hi,
After some tests, I seem to have several problems:

1. On the phone, when I traceroute 8.8.8.8, **it does not go to the proxy host I set.** That should show as the first hop, shouldn't it? Though, on the phone, I set the phone to use wifi + set manually proxy host name to my host and port (8081). I did verify that I can ping the proxy host from the smartphone. What's wrong with this?

2. When I add the debug: true, I get errors for instance when I try to get the CA certificate via http://myhostname:8082/ca.pem. Note **this is just a test, because I have already added the certificate manually on the phone** (and have verified it is listed ;)

Modification in example.logTraffic.coffee:
```
15c15
< server = new PokemonGoMITM port: 8081
---
> server = new PokemonGoMITM port: 8081, debug: true
```

Then npm start again. 
If I launch Pokemon Go, I only get an "HTTPS_CLIENT_ERROR on" error (with nothing afterwards!). But perhaps that's normal if my proxy isn't correctly set.
If from a shell on the smartphone I do a wget on http://myhostname:8082/ca.pem, or http://myhostname:8082/, I get various errors.

```
> pokemon-go-mitm@2.0.0 start /home/axelle/softs/pokemon-go-mitm-node
> coffee example.logTraffic.coffee

[+++] PokemonGo MITM [++++]
[+] Resolving pgorelease.nianticlabs.com
[+] Resolving android.clients.google.com
[+] Resolving sso.pokemon.com
[+] Resolving storage.googleapis.com
[+] Resolving done
[+] Virtual endpoint listening on 8082
[!] -> ENDPOINT USAGE: configure 'custom endpoint' in pokemon-go-xposed
[+] Proxy listening on 8081
[!] -> PROXY USAGE: make sure to have .http-mitm-proxy/certs/ca.pem installed on your device
[-] HTTPS_CLIENT_ERROR on :
[+] Handling request to virtual endpoint
[-] RequestError: Error: Argument error, options.body.
[+] Handling request to virtual endpoint
[-] RequestError: Error: Argument error, options.body.
[-] HTTPS_CLIENT_ERROR on :
[-] PROXY_TO_SERVER_REQUEST_ERROR on /ca.pem:
[+] Handling request to virtual endpoint
[-] RequestError: Error: Argument error, options.body.
[-] PROXY_TO_SERVER_REQUEST_ERROR on /:
```

Thanks for your help.

**Comment by trisk** [comment]
> On the phone, when I traceroute 8.8.8.8, it does not go to the proxy host I set. That should show as the first hop, shouldn't it? Though, on the phone, I set the phone to use wifi + set manually proxy host name to my host and port (8081). I did verify that I can ping the proxy host from the smartphone. What's wrong with this?
> 

IP routing is not affected by proxies. The proxy configuration is internal to the Android networking APIs.

> When I add the debug: true, I get errors for instance when I try to get the CA certificate via http://myhostname:8082/ca.pem. Note this is just a test, because I have already added the certificate manually on the phone (and have verified it is listed ;)

You are running 2.0.0, which is before I added the `/ca.pem` support.

**Comment by cryptax** [comment]
Ok, well then, I'm a bit stuck, aren't I?

This debug line with no more is not sufficient... 
```
[-] HTTPS_CLIENT_ERROR on :
```
Anything else I can try than that "debug: true" ?

**Comment by trisk** [comment]
Did you try updating to the current master branch? Also if you could test patched 0.33.0...

**Comment by trisk** [comment]
Login works fine for me with normal proxy mode or custom endpoint mode on 0.33.0 and 0.35.0.

**Comment by trisk** [comment]
I should say, PTC login works, although if you get far enough to send GetPlayer I assume Google login would also have succeeded.

**Comment by trisk** [comment]
This is almost certainly a connectivity issue to the pgo endpoint (e.g. banned network) so closing for now.

**Comment by fabfakegon** [comment]
http://prntscr.com/cetd3c
