### ISSUE TITLE
RPI CA Issues

### ISSUE THREAD

**Issue by thelemonenergy** [rastapasta/pokemon-go-mitm#187]
First thing to say: Yes i read the readme and did all steps.
when i try the first line of openssl genrsa...
I get an error saying:

.http-mitm-proxy/keys/ca.private.key:no such file or directory
1996347280:error:02001002:system library:fopen:No such file or directory:bbs_file.c:391:fopen('.http-mitm-proxy/keys/ca.private.key','w')
1996347280:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:393:

I googled but was not lucky now.
I typed this error message, so dont mind any typos.

**Comment by thelemonenergy** [comment]
sudo or not doesnt matter

**Comment by rastapasta** [comment]
hey @thelemonenergy, thanks for the kind issue report :) maybe the folders weren't created - just try a **mkdir -p .http-mitm-proxy/keys .http-mitm-proxy/certs**

**Comment by trisk** [comment]
Run `npm start' should create the directory, if not `mkdir -p .http-mitm-proxy/keys`. Don't use `sudo`.

**Comment by thelemonenergy** [comment]
i tried creating the dir now, but still get the same issue

**Comment by trisk** [comment]
What is the error message now? If the directory exists you will not see the same error.

**Comment by thelemonenergy** [comment]
npm start made some problems so i went with coffee example... which woked fine then.
My openssl genrsa does still have exactly that error message even if the folder exists

**Comment by trisk** [comment]
You are running a version of Node.js that does not support recent JavaScript/ECMAScript dialects. Try Node 4.0.0 or later.
If `openssl genrsa` is producing the same exact error, what is the output of:
`ls -ld .http-mitm-proxy/keys && touch .http-mitm-proxy/keys/ca.private.key`

**Comment by thelemonenergy** [comment]
I just purged and autoremoved node.js and reinstalled it via apt-get, i wont get a never version on raspberry pi i guess.

**Comment by trisk** [comment]
Try https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions which supports the armhf platform. I cannot help further with Node.js installation but you can try your distro's support channel/forum.

**Comment by thelemonenergy** [comment]
Ok, the problem is nodev4.x is not supported yet with ARMv8x64 (Raspberry Pi 3), Because Raspian OS is 32 BIT based. Im Running Ubuntu Core and will post my solution here when im finished.

**Comment by thelemonenergy** [comment]
http://resolvethis.com/how-to-install-nodejs-on-raspberry-pi-3/
This seems to be the Solution

**Comment by thelemonenergy** [comment]
It is not the Solution. Node is now on V5.0. Please Help 

at Function.Module.runMain (module.js:457:10)
  at startup (node.js:136:18)
  at node.js:972:3


npm ERR! Linux 4.1.18-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! pokemon-go-mitm@2.0.0 start: `coffee example.logTraffic.coffee`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pokemon-go-mitm@2.0.0 start script 'coffee example.logTraffic.coffee'.
npm ERR! This is most likely a problem with the pokemon-go-mitm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     coffee example.logTraffic.coffee
npm ERR! You can get their info via:
npm ERR!     npm owner ls pokemon-go-mitm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/thelemonenergy/pokemon-go-mitm-node/npm-debug.log

**Comment by trisk** [comment]
Did you delete the `node_modules` directory and re-run `npm install` after upgrading? If the problem still occurs, include the whole error message or log file.

**Comment by thelemonenergy** [comment]
@trisk @rastapasta I love you all. It works now

**Comment by trisk** [comment]
Glad to hear that! :)
