### ISSUE TITLE
Certificate 

### ISSUE THREAD

**Issue by TheJaake** [rastapasta/pokemon-go-mitm#188]
Okay, so I am new to this stuff but I am on Linux and I don't know where to download/get the certificate I generated...  I did everything correct but I am stuck at this... 
[+++] PokemonGo MITM [++++]
[+] Virtual endpoint listening on 8082
[!] -> ENDPOINT USAGE: configure 'custom endpoint' in pokemon-go-xposed
[+] Proxy listening on 8081
[!] -> PROXY USAGE: make sure to have .http-mitm-proxy/certs/ca.pem installed on your device

Where do i get the certificate??!  D:

**Comment by TheJaake** [comment]
Sorry I found the solution to this...  No need to answer

**Comment by gwarfan07** [comment]
how did you figure this out?

**Comment by rastapasta** [comment]
follow the README:
Run npm start (or coffee example.logTraffic.coffee) to generate a CA certificate
Download the generated certificate from the started server via http://host:8082/ca.crt (or copy the file .http-mitm-proxy/certs/ca.pem)
Add the certificate to the "trusted certificates" of your mobile (for "VPN and apps" on Android)

**Comment by gwarfan07** [comment]
I tried that and says no Path for host8082
