### ISSUE TITLE
How to configure custom endpoint without root

### ISSUE THREAD

**Issue by thelemonenergy** [rastapasta/pokemon-go-mitm#192]
[+] Virtual endpoint listening on 8082
[!] -> ENDPOINT USAGE: configure 'custom endpoint' in pokemon-go-xposed

I use an unsigned version 0.33 
Certificate is installed. 
Some of the example scripts work, others wont have any effect on the client. Is this because of the missing xposed?

**Comment by rastapasta** [comment]
all is good when some are working, will update the text so its clear to use either or.
which ones aren't working? we have to clean up a bit, as all requestHandlers currently can't update the data sent to the api (-> resigning). Cheers!

**Comment by thelemonenergy** [comment]
What did work so far:
example.ingameRadar.coffee
example.replacePokemons.coffee
example.pokemonIVdisplay.coffee
example.replacePokeStops.coffee


What had no effect on the client:
example.alwaySuperThrow.coffee
example.extendPokemonRange.coffee
example.autoReleaseWeakerPokemon.coffee
example.showPokeStopTime.coffee
example.visitPokeStop.coffee

**Comment by rastapasta** [comment]
Thanks for the list - yey, all of them use the currently disabled request altering as the MITM doesn't support resigning (yet). There might be an update to that soon! Sorry for the inconvenience and cheers!
