### ISSUE TITLE
how to use the examples..

### ISSUE THREAD

**Issue by Banginpadr** [rastapasta/pokemon-go-mitm#200]
i need on knowing how to use the examples. do i need to put then in the lib folder or something??

**Comment by rastapasta** [comment]
what a wonderful #200th issue - please stick to the readme - its all in there.

**Comment by Banginpadr** [comment]
im a nob. i had spent 8 hours trying to run the server (installing everything from scratch) fixing mysql problems ect. now 2 more hours trying to figureout how to use the examples. in readme.md i don't see anything, find or understood the steps. trust me the last thing i wanted to do was ask. because when you ask, normally people instead of taking the time to answer/help you, will use it to tell  you go do this go do that.

**Comment by rastapasta** [comment]
sorry for being a bit harsh, but you can't imagine how many not-technical-issue reports arrived here the last couple of weeks while working full-time on another project .. :) this is a very technical project to inspect and understand the workings of PoGO to build other things on top of it.

running the examples just requires to type 'coffee example.XYZ.coffee' in the main project folder if everything is set up! or just 'npm start' to start the logTraffic example.

Good luck and sorry that my temperament hit you :)

**Comment by jmoriau** [comment]
@rastapasta There's really no need to apologize, this is **not** an issue. 

@Banginpadr In the middle of the README it's written:

```
Run npm start (or coffee example.logTraffic.coffee) to generate a CA certificate
```

Granted it says "to generate a CA certificate" and not "to run a script" but still, anyone with even the most basic programming knowledge would have understood what it did when you ran it the first time.
Also it's common to search the previous issues before opening a new one, your question might have already asked.
With a simple search like this [coffee](https://github.com/rastapasta/pokemon-go-mitm/issues?page=2&q=is%3Aissue+is%3Aopen+is%3Aclosed+coffee&utf8=%E2%9C%93) you could have found #139 #95 #80 #81 and more. Which all answer your question.

**Comment by Banginpadr** [comment]
thank you so much for your work. i can only imagine how much of your time this is taking. after your answered me i think i know what to do now. thank you again my man.

**Comment by Banginpadr** [comment]
@jmoriau like i said IM A NOB. i just didn't understand how to use all the examples. now he told me how to so don't worry. 
PS: i read every questions before making mines. just to not have more question to ask since i didn't find anything that's why i asked.
