### ISSUE TITLE
Our servers are humbled by your incredible response

### ISSUE THREAD

**Issue by ovodilen** [rastapasta/pokemon-go-mitm#201]
Hi!

I try connect pokemon go on phone to example.LogTraffic.js, but "Our servers are humbled.."

linux-65c6:/home/ezzi/pokemon-go-mitm-node # node example.logTraffic.js
[+++] PokemonGo MITM [++++]
[+] Resolving pgorelease.nianticlabs.com
[+] Resolving android.clients.google.com
[+] Resolving sso.pokemon.com
[+] Resolving storage.googleapis.com
[+] Resolving done
[+] Virtual endpoint listening on 8082
[!] -> ENDPOINT USAGE: configure 'custom endpoint' in pokemon-go-xposed
[+] Proxy listening on 8081
[!] -> PROXY USAGE: install http://<proxy>:8082/ca.pem as a trusted certificate on your device
[+++] GET request for /ca.pem
[-] HTTPS_CLIENT_ERROR on :
[-] HTTPS_CLIENT_ERROR on :
[-] HTTPS_CLIENT_ERROR on :

**Comment by rastapasta** [comment]
Hey @ovodilen, have u installed the certificate to your mobile's trusted ones? Cheers!

**Comment by ovodilen** [comment]
yes, certificate is installed

**Comment by trisk** [comment]
How did you configure the proxy on your phone?

**Comment by ovodilen** [comment]
directly wi-fi android

**Comment by ovodilen** [comment]
certificate is generated anew each time at server startup?

**Comment by trisk** [comment]
No, it is generated once. Make sure you are using the right port (8081) in your proxy settings and have cert pinning disabled for the app.

**Comment by ovodilen** [comment]
port proxy settings wi-fi on phone 8081.
how check pinning disabled for the app?

**Comment by jmoriau** [comment]
@ovodilen please read the README, specifically this part [setting up your device](https://github.com/rastapasta/pokemon-go-mitm#setting-up-your-device) **before** opening an issue. *sigh*

**Comment by ovodilen** [comment]
I did everything according to these instructions

**Comment by krokofant** [comment]
> directly wi-fi android

Try the VPN / App option when installing the cert.

**Comment by ovodilen** [comment]
after installed pre-patch version 0.33 fine work Ж:)
