### ISSUE TITLE
GetPlayer returns response with Status Code 102

### ISSUE THREAD

**Issue by WalkaboutGo** [rastapasta/pokemon-go-mitm#208]
I'm using the 0.33.0 patched APK that you posted in [1] on a Samsung Galaxy S4. I booted up `example.logTraffic.coffee` just to verify that I had everything setup correctly with my proxy configuration. I've verified by going to various HTTPS websites that the certificates presented are signed by the MITM CA [2]. When I launch the app, it makes a few requests to unity and so on, but the first call to the GetPlayer API fails. The log looks like the below snippet (I added lines starting with [_]). This other project [3] seems to suggest this response code corresponds to an invalid auth token. Any idea what might be going on here? 

*Edit: I turned off the network proxy, removed the CA cert, and rebooted the phone. It looks like I just plain can't log in. This makes me think there is a problem with the patched APK.*

```
[_] Connecting pgorelease.nianticlabs.com:443
[+++] Request to /plfe/rpc
[+] Request for action GetPlayer: 
{}
[<-] Request for GetPlayer  {} 

[+] Waiting for response...
[_] Recived a response chunk
[_] Response received
[_] Raw Response { status_code: 102,
  unknown6: [],
  returns: [],
  : [] }
```

[1] https://github.com/rastapasta/pokemon-go-mitm/issues/69#issuecomment-238457389
[2] I've noticed that sometimes, just after visiting a unique domain, the certificate generated is not yet valid on the phone due to clock skew. I'll open an issue with your dependency to generate them 5 minutes in the past. I've account for this before cutting this issue.
[3] https://github.com/AeonLucid/POGOLib/blob/master/POGOLib/Net/RPCClient.cs#L373

**Comment by trisk** [comment]
That's normal when the auth ticket or token in the request has expired; the app will retry the same request ID with a fresh SSO token (and get an auth ticket in the successful response).

**Comment by WalkaboutGo** [comment]
Hmm, I've left it go for nearly an hour with no change in behavior

**Comment by trisk** [comment]
So the app gets stuck instead of retrying the GetPlayer request? Are you using a PTC or Google account? AFAIK either should work with the cert installed (the cert unpinning patch does not affect the connections used for auth, but they're not pinned either).

**Comment by WalkaboutGo** [comment]
Using a Google Account. 

This is very strange. I mentioned in my edit above that I had removed the ca cert, disabled the network proxy and rebooted to verify that I couldn't log in. So I went and installed the Xposed framework and then rebooted to finish that installation. I had not yet installed the pokemon-mitm Xposed module when I saw your last response. So I figured I would verify one more time. I installed the CA cert, turned on the network proxy settings, and opened chrome to verify that www.google.com was signed by the mitm CA. It was, but chrome was not trusting it. I had to reboot before chrome would accept the mitm CA signed cert for google.com. After that, I was able to log right in to pokemon go with no issue. 

Super strange. 

I verified before I opened this issue that chrome was showing google.com as trusted and signed by the mitm CA. Other than installing the Xposed framework (not the module) and rebooting a few times, I don't know what changed.

**Comment by WalkaboutGo** [comment]
I guess this issue is resolved then. My suggestion to anyone who finds this in the future is to reboot a few times after installing the CA cert to be really, really certain that all applications are aware of the updated list of trusted CAs

**Comment by trisk** [comment]
Glad to hear it worked out. I'll add the tip to the troubleshooting instructions, thanks!
