### ISSUE TITLE
QUESTION - Is there anywhere a list of known static fields and their current expected values?

### ISSUE THREAD

**Issue by Kermel** [rastapasta/pokemon-go-mitm#213]
Just a question before I spend hours attempting to compile and run the tool myself :) (I have only windows, so the hard way :-))
(btw. is it possible to use android emulators instead of the real phones ? (e.g. MEMU or similar) - has anyone tried this?)

Now to the question:
- is there possibly any actual list of known static fields and the values expected by pogo servers within the current verson of the app?
- for example Unknown25, hash used in DownloadSettings request etc. ?

Many thanks for info

**Comment by trisk** [comment]
The comments in the AeonLucid/POGOProtos proto files explain some of the static values.

Reople have reported using emulators (Nox, Genymotion and Bluestacks) but I wouldn't really recommend it.
