### ISSUE TITLE
Read-only detection

### ISSUE THREAD

**Issue by imapokemon4** [rastapasta/pokemon-go-mitm#215]
@rastapasta  
Is it possible for me to be detected while using [Trisk's pre-patched 0.35.0 APK](https://github.com/rastapasta/pokemon-go-mitm/issues/69#issuecomment-238457389) while using mitm to only read what the server sends to my device?

**Comment by trisk** [comment]
Google auth sends the signature for the app, so you need to use the proxy mode to override the signature if you use a modified APK with a Google account. Aside from that, the only issue is the connection will be coming from the address of the computer with the proxy rather than your phone.
