### ISSUE TITLE
Unable to authenticate. Please try again

### ISSUE THREAD

**Issue by tirajetwng** [rastapasta/pokemon-go-mitm#216]
I got this message when I try to login. 
please help me
`
sudo coffee example.alwaySuperThrow.coffee 
[+++] PokemonGo MITM [++++]

[+] Resolving pgorelease.nianticlabs.com
[+] Resolving android.clients.google.com
[+] Resolving sso.pokemon.com
[+] Resolving storage.googleapis.com
[+] Resolving done
[+] Virtual endpoint listening on 8082
[!] -> ENDPOINT USAGE: configure 'custom endpoint' in pokemon-go-xposed
[+] Proxy listening on 8081
[!] -> PROXY USAGE: install http://<host>:8082/ca.crt as a trusted certificate
[-] PROXY_TO_SERVER_REQUEST_ERROR on /plfe/rpc:
[-] PROXY_TO_SERVER_REQUEST_ERROR on /plfe/rpc:
[-] PROXY_TO_SERVER_REQUEST_ERROR on /plfe/rpc:
`

**Comment by tirajetwng** [comment]
`[+++] PokemonGo MITM [++++]
[+] Resolving pgorelease.nianticlabs.com
[+] Resolving android.clients.google.com
[+] Resolving sso.pokemon.com
[+] Resolving storage.googleapis.com
[+] Resolving done
[+] Virtual endpoint listening on 8082
[!] -> ENDPOINT USAGE: configure 'custom endpoint' in pokemon-go-xposed
[+] Proxy listening on 8081
[!] -> PROXY USAGE: install http://<host>:8082/ca.crt as a trusted certificate
[-] PROXY_TO_SERVER_REQUEST_ERROR on /plfe/rpc:
[-] PROXY_TO_SERVER_REQUEST_ERROR on /plfe/rpc:
[-] PROXY_TO_SERVER_REQUEST_ERROR on /plfe/rpc:
`

**Comment by trisk** [comment]
1. Don't run this as root. Using `sudo` with commands randomly is *dangerous*
2. Check if you can actually reach https://pgorelease.nianticlabs.com/plfe/ from this computer
3. You can't modify requests because of the validation, so example.alwaySuperThrow.coffee  is currently not useful
