### ISSUE TITLE
How did he did that?

### ISSUE THREAD

**Issue by thepokemaster** [rastapasta/pokemon-go-mitm#220]
Today i watched youtube and i saw this youtuber fuzed and he made a fuck ton of legandery pokemons to spawn near him i know how to spaen mewtwo but only with changing the models
I know it is just a visual but can someone pls help me with what script he used? 
I have no idea how managed to do this:
https://youtu.be/W-Y6QwepWwU
At the middle of the video you can se he spawned near him a ton of mewtwo's

**Comment by thepokemaster** [comment]
Spawn*

**Comment by trisk** [comment]
The GetMapObjects response contains the list of `wild_pokemons` and `catchable_pokemons` for each cell. You can add new pokemon encounters or change existing ones there.

**Comment by thepokemaster** [comment]
Thank you
