### ISSUE TITLE
Request Error

### ISSUE THREAD

**Issue by nogard230** [rastapasta/pokemon-go-mitm#221]
a new error for me... cry i_i

[+++] PokemonGo MITM [++++]
[+] Virtual endpoint listening on 8082
[!] -> ENDPOINT USAGE: configure 'custom endpoint' in pokemon-go-xposed
[+] Proxy listening on 8081
[!] -> PROXY USAGE: install http://<host>:8082/ca.crt as a trusted certificate
[-] RequestError: Error: getaddrinfo ENOTFOUND pgorelease.nianticlabs.comhttp pgorelease.nianticlabs.comhttp:443

**Comment by trisk** [comment]
Bad DNS configuration on your computer.

**Comment by trisk** [comment]
It looks almost like you have the Xposed custom endpoint configured but also have the system proxy enabled. Should be one or the other.

**Comment by nogard230** [comment]
on logTrafficFull: 
 PROXY_TO_SERVER_REQUEST_ERROR on /plfe/rpc: { [Error: connect EMFILE 192.168.14.7:8081 - Local (undefined:undefined)]
  code: 'EMFILE',
  errno: 'EMFILE',
  syscall: 'connect',
  address: '192.168.14.7',
  port: 8081 }

i'm used xposed and proxydroid, and ubuntu server.

**Comment by trisk** [comment]
Don't use proxydroid if you configured Xposed.

**Comment by nogard230** [comment]
proxydroid uninstaled:
On device: failed to log in
on ubuntu: [-] PROXY_TO_SERVER_REQUEST_ERROR on /plfe/rpc: { [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }

**Comment by trisk** [comment]
Can you actually reach https://pgorelease.nianticlabs.com/plfe/ from this computer? Is it at your home?

**Comment by nogard230** [comment]
Yes.
 "Dude, this is the Player Frontend. "

**Comment by trisk** [comment]
To recap, you have `yourhost:8082` set as the custom endpoint in xposed, right? I think only the regular proxy on 8081 will print "PROXY_TO_SERVER_REQUEST_ERROR" in errors.

**Comment by nogard230** [comment]
my endpoint set to 8081 on xposed. If set it to 8082, it's log normally, but the scripts not effect on app.

(thanks for patience and ansawer ;) @trisk )

**Comment by nogard230** [comment]
Yaaaahh, 
Thanks so much, I selected for 8082 and accept the ports(8081,8082) in iptables.
\o/
thanks @trisk and @rastapasta

**Comment by trisk** [comment]
Glad to hear it's working, if there are problems with the scripts please open another bug. 😄
