### ISSUE TITLE
Sorta stuck, having a bunch of issues with Ubuntu.

### ISSUE THREAD

**Issue by HawkinsNWT** [rastapasta/pokemon-go-mitm#223]
I'm trying to set up the Coffee Server, but each time I put in `coffee example.logTraffic.coffee`,

 I keep running into this: http://imgur.com/a/aYttW

Anyone know what is causing this issue, or have a resolution? Fairly new to this kind of stuff so I don't know too much about this topic. Thanks in advanced!

**Comment by trisk** [comment]
You probably have stuff left over from a different version of Node in `node_modules`; delete the `node_modules` directory and re-run `npm-install`

**Comment by trisk** [comment]
Also, uh, you know you can copy and paste from your terminal by highlighting text and using the middle mouse button to paste, right? Or if you don't have a middle button, right-click or Ctrl-Shift-C in the terminal after highlighting. 😄

**Comment by gwarfan07** [comment]
if anyone can help me i get this error when running coffee example.logTraffic.coffee 
 "/usr/bin/env: 'node' : no such file or directory"

**Comment by trisk** [comment]
If this is a Debian-based system, try: `sudo apt-get install nodejs-legacy`

**Comment by gwarfan07** [comment]
i fixed it you have to run command sudo ln -s /usr/bin/nodejs /usr/bin/node then run coffee example.logTraffic.coffee then run npm install and then run coffee example.logTraffic.coffee and it will work
