### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by EricPaulZ467** [rastapasta/pokemon-go-mitm#228]
Today, I finished installing this. All of the process run very well but there is an error that keep making stressed, every time I type in 'npm install' it comes out too many errors. This is the log for it.

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'pokemon-go-mitm' ]
2 info using npm@3.10.3
3 info using node@v6.5.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData pokemon-go-mitm
8 silly fetchNamedPackageData pokemon-go-mitm
9 silly mapToRegistry name pokemon-go-mitm
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'pokemon-go-mitm',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'pokemon-go-mitm',
12 silly mapToRegistry   name: 'pokemon-go-mitm',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/pokemon-go-mitm
14 verbose request uri https://registry.npmjs.org/pokemon-go-mitm
15 verbose request no auth needed
16 info attempt registry request try #1 at 10:51:29
17 verbose request id 8cfdcddd760f23d5
18 http request GET https://registry.npmjs.org/pokemon-go-mitm
19 http 200 https://registry.npmjs.org/pokemon-go-mitm
20 verbose headers { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
20 verbose headers   etag: '"2S1775UARVUKSVJRTI6TDAUMJ"',
20 verbose headers   'content-type': 'application/json',
20 verbose headers   'content-encoding': 'gzip',
20 verbose headers   'cache-control': 'max-age=300',
20 verbose headers   'content-length': '5357',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Sat, 03 Sep 2016 02:51:25 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-fra1248-FRA',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1472871084.611180,VS0,VE439',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 200,
21 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
21 silly get     etag: '"2S1775UARVUKSVJRTI6TDAUMJ"',
21 silly get     'content-type': 'application/json',
21 silly get     'content-encoding': 'gzip',
21 silly get     'cache-control': 'max-age=300',
21 silly get     'content-length': '5357',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Sat, 03 Sep 2016 02:51:25 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-fra1248-FRA',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1472871084.611180,VS0,VE439',
21 silly get     vary: 'Accept-Encoding' } ]
22 verbose get saving pokemon-go-mitm to C:\Users\kami bin kita\AppData\Roaming\npm-cache\registry.npmjs.org\pokemon-go-mitm\.cache.json
23 verbose correctMkdir C:\Users\kami bin kita\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
24 silly install normalizeTree
25 silly loadCurrentTree Finishing
26 silly loadIdealTree Starting
27 silly install loadIdealTree
28 silly cloneCurrentTree Starting
29 silly install cloneCurrentTreeToIdealTree
30 silly cloneCurrentTree Finishing
31 silly loadShrinkwrap Starting
32 silly install loadShrinkwrap
33 silly loadShrinkwrap Finishing
34 silly loadAllDepsIntoIdealTree Starting
35 silly install loadAllDepsIntoIdealTree
36 silly rollbackFailedOptional Starting
37 silly rollbackFailedOptional Finishing
38 silly runTopLevelLifecycles Starting
39 silly runTopLevelLifecycles Finishing
40 silly install printInstalled
41 verbose stack Error: Refusing to install pokemon-go-mitm as a dependency of itself
41 verbose stack     at checkSelf (C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:53:14)
41 verbose stack     at Array.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
41 verbose stack     at LOOP (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
41 verbose stack     at chain (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
41 verbose stack     at Array.forEach (native)
41 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
41 verbose stack     at Array.forEach (native)
41 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
42 verbose cwd D:\Javla\Mewtwo\Worksheet\pokemon-go-mitm-node
43 error Windows_NT 6.1.7601
44 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "pokemon-go-mitm"
45 error node v6.5.0
46 error npm  v3.10.3
47 error code ENOSELF
48 error Refusing to install pokemon-go-mitm as a dependency of itself
49 error If you need help, you may report this error at:
49 error     <https://github.com/npm/npm/issues>
50 verbose exit [ 1, true ]

**Comment by trisk** [comment]
Looks like you typed `npm install pokemon-go-mitm` instead of the correct `npm install`.

**Comment by EricPaulZ467** [comment]
It still doesn't work, have any solutions?

**Comment by trisk** [comment]
you need to provide more information than "it doesn't work"

**Comment by Vankxr** [comment]
Same happens with me
It also gives errors when trying to npm install coffee

**Comment by EricPaulZ467** [comment]
I *THINK* that I found the solution, if you go to "https://github.com/rastapasta/pokemon-go-mitm/" and you scroll down you will see this : "npm package : 2.1.0". I think this is the problem because I'm using version 3.10.3. Can someone test this out and comment down what happened?

**Comment by trisk** [comment]
That is not the problem. You have not provided the actual error message.

**Comment by EricPaulZ467** [comment]
So how do you fix it?

**Comment by jmoriau** [comment]
**sigh**
```You have not provided the actual error message you are seeing.```

**Comment by EricPaulZ467** [comment]
Okay, this is the actual error message in command prompt :

> > node-protobuf@1.3.3 install D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node\nod
e_modules\pokemongo-protobuf\node_modules\node-protobuf
> node-gyp rebuild


D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node\node_modules\pokemongo-protobuf\n
ode_modules\node-protobuf>if not defined npm_config_node_gyp (node "C:\Program F
iles\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\n
ode-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  init.cpp
  native.cpp
C:\Users\kami bin kita\.node-gyp\4.5.0\include\node\v8.h(18): fatal error C1083
: Cannot open include file: 'stddef.h': No such file or directory (compiling so
urce file ..\src\init.cpp) [D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node\node
_modules\pokemongo-protobuf\node_modules\node-protobuf\build\protobuf.vcxproj]
C:\Users\kami bin kita\.node-gyp\4.5.0\include\node\v8.h(18): fatal error C1083
: Cannot open include file: 'stddef.h': No such file or directory (compiling so
urce file ..\src\native.cpp) [D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node\no
de_modules\pokemongo-protobuf\node_modules\node-protobuf\build\protobuf.vcxproj
]
  parse.cpp
  serialize.cpp
C:\Users\kami bin kita\.node-gyp\4.5.0\include\node\v8.h(18): fatal error C1083
: Cannot open include file: 'stddef.h': No such file or directory (compiling so
urce file ..\src\serialize.cpp) [D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node
\node_modules\pokemongo-protobuf\node_modules\node-protobuf\build\protobuf.vcxp
roj]
C:\Users\kami bin kita\.node-gyp\4.5.0\include\node\v8.h(18): fatal error C1083
: Cannot open include file: 'stddef.h': No such file or directory (compiling so
urce file ..\src\parse.cpp) [D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node\nod
e_modules\pokemongo-protobuf\node_modules\node-protobuf\build\protobuf.vcxproj]
  win_delay_load_hook.cc
C:\Program Files\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C1083: Ca
nnot open include file: 'ctype.h': No such file or directory (compiling source
file C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_del
ay_load_hook.cc) [D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node\node_modules\p
okemongo-protobuf\node_modules\node-protobuf\build\protobuf.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed wit
h exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node\node_modules\pokemon
go-protobuf\node_modules\node-protobuf
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-protobuf@1.3.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-protobuf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node\npm-debug.log

**Comment by EricPaulZ467** [comment]
Okay, this is the actual error message in command prompt:

> > node-protobuf@1.3.3 install D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node\nod
e_modules\pokemongo-protobuf\node_modules\node-protobuf
> node-gyp rebuild
D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node\node_modules\pokemongo-protobuf\n
ode_modules\node-protobuf>if not defined npm_config_node_gyp (node "C:\Program F
iles\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\n
ode-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  init.cpp
  native.cpp
C:\Users\kami bin kita\.node-gyp\4.5.0\include\node\v8.h(18): fatal error C1083
: Cannot open include file: 'stddef.h': No such file or directory (compiling so
urce file ..\src\init.cpp) [D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node\node
_modules\pokemongo-protobuf\node_modules\node-protobuf\build\protobuf.vcxproj]
C:\Users\kami bin kita\.node-gyp\4.5.0\include\node\v8.h(18): fatal error C1083
: Cannot open include file: 'stddef.h': No such file or directory (compiling so
urce file ..\src\native.cpp) [D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node\no
de_modules\pokemongo-protobuf\node_modules\node-protobuf\build\protobuf.vcxproj
]
 parse.cpp
  serialize.cpp
C:\Users\kami bin kita\.node-gyp\4.5.0\include\node\v8.h(18): fatal error C1083
: Cannot open include file: 'stddef.h': No such file or directory (compiling so
urce file ..\src\serialize.cpp) [D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node
\node_modules\pokemongo-protobuf\node_modules\node-protobuf\build\protobuf.vcxp
roj]
C:\Users\kami bin kita\.node-gyp\4.5.0\include\node\v8.h(18): fatal error C1083
: Cannot open include file: 'stddef.h': No such file or directory (compiling so
urce file ..\src\parse.cpp) [D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node\nod
e_modules\pokemongo-protobuf\node_modules\node-protobuf\build\protobuf.vcxproj]
  win_delay_load_hook.cc
C:\Program Files\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C1083: Ca
nnot open include file: 'ctype.h': No such file or directory (compiling source
file C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_del
ay_load_hook.cc) [D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node\node_modules\p
okemongo-protobuf\node_modules\node-protobuf\build\protobuf.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed wit
h exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node\node_modules\pokemon
go-protobuf\node_modules\node-protobuf
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! node-protobuf@1.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-protobuf@1.3.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-protobuf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     D:\AdminPC\Mewtwo\Worksheet\pokemon-go-mitm-node\npm-debug.log

**Comment by EricPaulZ467** [comment]
Sorry, didn't notice it. This is the actual error message in the command prompt:

> > node-protobuf@1.3.3 install D:\location\Mewtwo\Worksheet\pokemon-go-mitm-node\nod
e_modules\pokemongo-protobuf\node_modules\node-protobuf
> node-gyp rebuild


D:\location\Mewtwo\Worksheet\pokemon-go-mitm-node\node_modules\pokemongo-protobuf\n
ode_modules\node-protobuf>if not defined npm_config_node_gyp (node "C:\Program F
iles\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\n
ode-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  init.cpp
  native.cpp
C:\Users\AdminPC\.node-gyp\4.5.0\include\node\v8.h(18): fatal error C1083
: Cannot open include file: 'stddef.h': No such file or directory (compiling so
urce file ..\src\native.cpp) [D:\location\Mewtwo\Worksheet\pokemon-go-mitm-node\no
de_modules\pokemongo-protobuf\node_modules\node-protobuf\build\protobuf.vcxproj
]
  parse.cpp
C:\Users\AdminPC\.node-gyp\4.5.0\include\node\v8.h(18): fatal error C1083
: Cannot open include file: 'stddef.h': No such file or directory (compiling so
urce file ..\src\init.cpp) [D:\location\Mewtwo\Worksheet\pokemon-go-mitm-node\node
_modules\pokemongo-protobuf\node_modules\node-protobuf\build\protobuf.vcxproj]
  serialize.cpp
C:\Users\AdminPC\.node-gyp\4.5.0\include\node\v8.h(18): fatal error C1083
: Cannot open include file: 'stddef.h': No such file or directory (compiling so
urce file ..\src\parse.cpp) [D:\location\Mewtwo\Worksheet\pokemon-go-mitm-node\nod
e_modules\pokemongo-protobuf\node_modules\node-protobuf\build\protobuf.vcxproj]
  win_delay_load_hook.cc
C:\Users\AdminPC\.node-gyp\4.5.0\include\node\v8.h(18): fatal error C1083
: Cannot open include file: 'stddef.h': No such file or directory (compiling so
urce file ..\src\serialize.cpp) [D:\location\Mewtwo\Worksheet\pokemon-go-mitm-node
\node_modules\pokemongo-protobuf\node_modules\node-protobuf\build\protobuf.vcxp
roj]
C:\Program Files\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C1083: Ca
nnot open include file: 'ctype.h': No such file or directory (compiling source
file C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_del
ay_load_hook.cc) [D:\location\Mewtwo\Worksheet\pokemon-go-mitm-node\node_modules\p
okemongo-protobuf\node_modules\node-protobuf\build\protobuf.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed wit
h exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\location\Mewtwo\Worksheet\pokemon-go-mitm-node\node_modules\pokemon
go-protobuf\node_modules\node-protobuf
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! node-protobuf@1.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-protobuf@1.3.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-protobuf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\location\Mewtwo\Worksheet\pokemon-go-mitm-node\npm-debug.log

**Comment by trisk** [comment]
I can't help you set up node-protobuf. It looks like your Microsoft Visual C++ installation might be incomplete or messed up since it can't find `<stddef.h>`. Did you follow the link to the Windows instructions for that? https://github.com/fuwaneko/node-protobuf#windows

**Comment by EricPaulZ467** [comment]
I think that is the problem because in my Microsoft Visual C++ installation it says that some of the features weren't installed and I watched the video (https://www.youtube.com/watch?v=TWcZ2FYnZQo), where it teaches how to install RastaPasta MITM Proxy and I contacted him yesterday, he said that my Microsoft Visual C++  installation messed things up so he advised me to reinstall it. So thanks for the help!
