### ISSUE TITLE
How can i run 2 .coffee files at once? 

### ISSUE THREAD

**Issue by lukabaazovi** [rastapasta/pokemon-go-mitm#229]
for example i want to run example.ReplacePokestops and mewtwo script too

**Comment by trisk** [comment]
Make a new file that combines the `register...Handler` sections from both scripts. (This project is meant for people with a basic understanding of computer programming).

**Comment by lukabaazovi** [comment]
How? pls help me i am a noob at this

**Comment by trisk** [comment]
You will need to read and understand the scripts yourself, we can't teach you how to program.
