### ISSUE TITLE
'coffee example.logTraffic.coffee' doesn't seem to work out.

### ISSUE THREAD

**Issue by dkakkad12** [rastapasta/pokemon-go-mitm#231]
[+++] Pokemon MITM [++++]
[+] Virtual endpoint listening on 8082
[!] -> ENDPOINT USAGE: configure 'custom endpoint' in pokemon-go-xposed
[+] Proxy listening on 8081
[!] -> PROXY USAGE: install http;//<host>:8082/ca.crt as a trusted
certificate

And it ends just like that, I can't type in anything and I don't get any certificate either.

Thanks for assistance!

**Comment by trisk** [comment]
There is nothing to type. Set up your device to use the proxy or endpoint following the instructions.
