### ISSUE TITLE
HELP ME I HAVE a problem when a people transfers pokemons stop working

### ISSUE THREAD

**Issue by RBOY2017** [rastapasta/pokemon-go-mitm#237]
TypeError: Cannot read property 'contents' of undefined
  at PokemonGoMITM.getSession (C:\Users\rafa\Downloads\pokemon-go-mitm-node\lib\pokemon-go-mitm.coffee:394:26)
  at PokemonGoMITM.handleRequest (C:\Users\rafa\Downloads\pokemon-go-mitm-node\lib\pokemon-go-mitm.coffee:256:16)
  at C:\Users\rafa\Downloads\pokemon-go-mitm-node\lib\pokemon-go-mitm.coffee:229:28
  at C:\Users\rafa\Downloads\pokemon-go-mitm-node\node_modules\http-mitm-proxy\lib\proxy.js:968:12
  at C:\Users\rafa\Downloads\pokemon-go-mitm-node\node_modules\async\lib\async.js:181:20
  at Object.async.forEachOf.async.eachOf (C:\Users\rafa\Downloads\pokemon-go-mitm-node\node_modules\async\lib\async.js:233:13)
  at Object.async.forEach.async.each (C:\Users\rafa\Downloads\pokemon-go-mitm-node\node_modules\async\lib\async.js:209:22)
  at Proxy._onRequestEnd (C:\Users\rafa\Downloads\pokemon-go-mitm-node\node_modules\http-mitm-proxy\lib\proxy.js:967:9)
  at ProxyFinalRequestFilter.end (C:\Users\rafa\Downloads\pokemon-go-mitm-node\node_modules\http-mitm-proxy\lib\proxy.js:804:20)
  at IncomingMessage.onend (_stream_readable.js:511:10)
  at IncomingMessage.g (events.js:286:16)
  at emitNone (events.js:86:13)
  at IncomingMessage.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:974:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

[<-] Request for GetInventory  { last_timestamp_ms: '1473120088116', '$unknownFields': [] }

C:\Users\rafa\Downloads\pokemon-go-mitm-node\backup.coffee:27
        if (pokemon = item.inventory_item_data.pokemon_data) {
                                              ^

TypeError: Cannot read property 'pokemon_data' of undefined
  at PokemonGoMITM.<anonymous> (C:\Users\rafa\Downloads\pokemon-go-mitm-node\backup.coffee:19:42)
  at PokemonGoMITM.handleResponseAction (C:\Users\rafa\Downloads\pokemon-go-mitm-node\lib\pokemon-go-mitm.coffee:440:9)
  at PokemonGoMITM.handleResponse (C:\Users\rafa\Downloads\pokemon-go-mitm-node\lib\pokemon-go-mitm.coffee:343:26)
  at C:\Users\rafa\Downloads\pokemon-go-mitm-node\lib\pokemon-go-mitm.coffee:171:21
  at Gunzip.onEnd (zlib.js:227:5)
  at emitNone (events.js:91:20)
  at Gunzip.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:974:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

https://drive.google.com/open?id=0B3LDCi6Vh-2jbW5NZDRKd3NhVms VIDEO WITH THE PROBLEM

**Comment by trisk** [comment]
There's a minor bug in the session check I just fixed, but the main problem is the bug in your code I already explained to you.

**Comment by RBOY2017** [comment]
###
  Pokemon Go(c) MITM node proxy
  by Michael Strassburger <codepoet@cpan.org>

  This example replaces all your pokemons with Mew, Mewto, Dragonite, ...

  Be aware: this is just visible to you and won't gain you any special powers
            all display pokemons will act as their original ones
###

PokemonGoMITM = require './lib/pokemon-go-mitm'

server = new PokemonGoMITM port: 8081
	.addResponseHandler "GetInventory", (data) ->
		
		biggest = 151
		if data.inventory_delta
			for item in data.inventory_delta.inventory_items
				if pokemon = item.inventory_item_data.pokemon_data
					pokemon.pokemon_id = biggest--
					pokemon.cp = 20000

					break unless biggest
		data

.addResponseHandler "FortDetails", (data) ->
		data.name = "WELCOMD TO MARCIANOSTOP"
		data.description = "THE MARCIAN AVENUE 0808
		data.image_urls = ["https://scontent-atl3-1.cdninstagram.com/t51.2885-15/s750x750/sh0.08/e35/14145487_1606253873005231_1039741151_n.jpg?ig_cache_key=MTMyNjkyMDc1NzAwNzM2OTIxMw%3D%3D.2"]
		data
.addResponseHandler "GetInventory", (data) ->
    for item in data.inventory_delta.inventory_items
      if stats = item.inventory_item_data.player_stats

        stats.level = 101
        stats.experience = 520

    data

coughtIDs = []
server.addResponseHandler "CatchPokemon", (data) ->
    if "status" of data
        if data.status == "CATCH_SUCCESS"
            coughtIDs.push data.captured_pokemon_id
            data.capture_award.activity_type[1] = "ACTIVITY_POKEDEX_ENTRY_NEW"
            data.capture_award.xp = "0": 100, "1": 500
            data.capture_award.candy = "0": 3, "1": 0
            data.capture_award.stardust = "0": 100, "1": 0
            console.log("dataflata")
            console.log(JSON.stringify(data,null,4))
    data
server.addResponseHandler "GetInventory", (data) ->
    if "success" of data
        if data.success
            for item in data.inventory_delta.inventory_items
                if "pokemon_data" of item.inventory_item_data
                    if item.inventory_item_data.pokemon_data.id in coughtIDs
                        item.inventory_item_data.pokemon_data.pokemon_id = "DITTO"
                        item.inventory_item_data.pokemon_data.cp = 6000
                        item.inventory_item_data.pokemon_data.stamina = 221
                        item.inventory_item_data.pokemon_data.stamina_max = 221
                        item.inventory_item_data.pokemon_data.weight_kg = 122.28
                        item.inventory_item_data.pokemon_data.height_m = 2.07
                        item.inventory_item_data.pokemon_data.move_1 = "PSYCHIC"
                        item.inventory_item_data.pokemon_data.move_2 = "PSYSTRIKE"
                        item.inventory_item_data.pokemon_data.individual_attack = 30
                        item.inventory_item_data.pokemon_data.individual_defense = 20
                        item.inventory_item_data.pokemon_data.individual_stamina = 15
                if "pokedex_entry" of item.inventory_item_data
                    item.inventory_item_data.pokedex_entry.times_encountered = 1
                    item.inventory_item_data.pokedex_entry.times_captured = 1
                    item.inventory_item_data.pokedex_entry.pokemon_id = "DITTO"
                if "candy" of item.inventory_item_data
                    item.inventory_item_data.candy.family_id = "MEWTO"
                    item.inventory_item_data.candy.candy = 3
    data

server.addResponseHandler "GetMapObjects", (data) ->
    if "map_cells" of data
        cal = new Date()
        now = cal.getTime()
        for cell in data.map_cells
            for mon in cell.catchable_pokemons
                mon.pokemon_id = "MEWTWO"
                
            for mon in cell.wild_pokemons
                mon.pokemon_data.pokemon_id = "MEWTWO"
    data
server.addResponseHandler "Encounter", (data) ->
    if "status" of data
        if data.status == "ENCOUNTER_SUCCESS"
            data.wild_pokemon.pokemon_data.pokemon_id = "MEWTWO"
            data.wild_pokemon.pokemon_data.cp = 6000
            data.wild_pokemon.pokemon_data.weight_kg = 122
            data.wild_pokemon.pokemon_data.height_m = 2
            data.capture_probability.capture_probability['0'] = 0.0
            data.capture_probability.capture_probability['1'] = 0.0
            data.capture_probability.capture_probability['2'] = 0.1

    data

ignore = ['GetInventory', 'GetMapObjects', 'CatchPokemon', 'Encounter']

server.addRequestHandler "*", (data, action) ->
		console.log "[<-] Request for #{action} ", data, "\n" unless not (action in ignore)
		data

server.addResponseHandler "*", (data, action) ->
		console.log "[->] Response for #{action} ", JSON.stringify(data, null, 4), "\n" unless not (action in ignore)
		data
	.addRequestHandler "CatchPokemon", (data) ->

		data.normalized_reticle_size = 1.950
		data.spin_modifier = 0.850
		if data.hit_pokemon
			data.normalized_hit_position = 1.0

		data
CAN YOU SOLVE? HERE THE CODE

**Comment by jmoriau** [comment]
CAN YOU SOLVE? HERE THE CODE

No.
