### ISSUE TITLE
Request for GetPlayer 

### ISSUE THREAD

**Issue by shadowangelo** [rastapasta/pokemon-go-mitm#239]
I was able to run this on my ubuntu VM
but after i turned it off on the evening and booted it in the day after
i am experiencing this error.
deleted ealier installation and create another file. installed again. havin same issue. 
can someone help me out? if this question is already ask. pls link me to an answer. thank in advance
newbie here<<<

osboxes@osboxes:~/pokemon-go-mitm-node$ npm restart

 pokemon-go-mitm@2.1.0 start /home/osboxes/pokemon-go-mitm-node
 coffee example.logTraffic.coffee

[+++] PokemonGo MITM [++++]
[+] Virtual endpoint listening on 8082
[!] -> ENDPOINT USAGE: configure 'custom endpoint' in pokemon-go-xposed
[+] Proxy listening on 8081
[!] -> PROXY USAGE: install http://<host>:8082/ca.crt as a trusted certificate
[<-] Request for GetPlayer  { player_locale: { country: 'US', language: 'en' },
  '$unknownFields': [] } 

[<-] Request for CheckChallenge  {}
[-] RequestError: Error: tunneling socket could not be established, statusCode=404

**Comment by shadowangelo** [comment]
[+++] PokemonGo MITM [++++]
[+] Virtual endpoint listening on 8082
[!] -> ENDPOINT USAGE: configure 'custom endpoint' in pokemon-go-xposed
[+] Proxy listening on 8081
[!] -> PROXY USAGE: install http://<host>:8082/ca.crt as a trusted certificate
[<-] Request for GetPlayer  { player_locale: { country: 'US', language: 'en' },
  '$unknownFields': [] } 

[<-] Request for CheckChallenge  {} 

[-] RequestError: Error: tunneling socket could not be established, statusCode=404

pasted wrong logs. sorry. here

**Comment by shadowangelo** [comment]
@rastapasta 
do you have any idea aboout this sir?

**Comment by trisk** [comment]
Your proxy computer is on a banned network or has network problems. Can you reach https://pgorelease.nianticlabs.com/plfe/ from this computer?

**Comment by shadowangelo** [comment]
i managed to solve this problem by deleting my proxy on my VM. i forgot. i put a proxy to test tunneling via port 8081. i hope there will be no error after rebooting the VM again

**Comment by shadowangelo** [comment]
by the way. thank you.

**Comment by trisk** [comment]
cheers, I'll close this for now.
