### ISSUE TITLE
opening shop doesnt work with mitm proxy on (iOS)

### ISSUE THREAD

**Issue by AVVS** [rastapasta/pokemon-go-mitm#32]
using enhanced backend repo, but I assume that would be mitm's issue
in any case - could some1 else try and tell me?

**Comment by rastapasta** [comment]
thanks for noticing it! let' see, investigating..

**Comment by rastapasta** [comment]
Can open it, no request is sent from the app to the server to do so. Can you specify what exactly doesn't work or how to reproduce?

**Comment by AVVS** [comment]
Well, I press on the “shop” and I get a blank white screen.
If I don’t use the proxy - screen would populate with data

**Comment by rastapasta** [comment]
aaah, u're using ProxyDruid, ei?

**Comment by rastapasta** [comment]
it's the IP->hostname mapping issue - the CONNECT header to the proxy only contains the IP, not the hostname, so no valid cert can be generated before knowing the (encrypted) hostname.
before the shop opens (on android), the app communicates with storage.googleapis.com - which won't be mapped correctly (yet) on ProxyDruid. Can fix this if you could confirm that u're using it :)

**Comment by AVVS** [comment]
I'm using iOS actually, so I don't know anything about android :)

**Comment by rastapasta** [comment]
Damn, won't be able to help out the atm, sorry :)
