### ISSUE TITLE
Please Help - installation on Windows

### ISSUE THREAD

**Issue by Joesten** [rastapasta/pokemon-go-mitm#33]
I would really like to go through the steps and set this up that is my favorite game If someone could give a more detailed tutorial on how Windows: hard to compile - follow advices section it would be much help Thank you.

**Comment by ftpnz** [comment]
gettong protoc installed on windows isnt the issue (they have a great tutorial for that) its getting the libprotobuf enviromental path to run correctly. download the node-protobuf git repo and edit the bindings gyp replace the (ls)\lib with the path to you own library and also replace (ls)\includes to the path for your own protobuf includes


sorry if thats confusing its the only way i got it to install

**Comment by xlr82xs** [comment]
I would actually recommend downloading/installing the windows docker package (instructions available at https://docs.docker.com/engine/installation/windows/ ) and using that to install the "node" container ( docker run -d -p 8081:8081 -it node ) will do that for you, from there you can attach to the container, run a bash shell, follow the linux install instructions.
