### ISSUE TITLE
help getting to run behind bluestacks

### ISSUE THREAD

**Issue by ftpnz** [rastapasta/pokemon-go-mitm#37]
ok so i have the this working on windows (absolute pain) 
but only if i direct my mobile to my pc im wanting to get the mitm tool to run as proxy for bluestacks proxycap has been setup correctly but the mitm wont parse the data. any ideas? maybe a certificate error?

oh also is there any examples around for changing pokemon in an encounter? ie weedle shows up but you catch say mewtwo?

**Comment by trisk** [comment]
Can't help you with your setup, but here's an example for changing encounter data:
```
.addResponseHandler "Encounter", (data) ->
        console.log "encounter with pokemon", data
        if data.pokemon_data.pokemon_id = 'WEEDLE'
                data.pokemon_data.pokemon_id = 'MEWTWO'
        data
```
Obviously this only affects the Pokémon displayed during the encounter.
