### ISSUE TITLE
Add trusted certificates help

### ISSUE THREAD

**Issue by jpfelgueiras** [rastapasta/pokemon-go-mitm#55]
On the readme page it should have some help top install the certificate.

**Comment by jpfelgueiras** [comment]
For me the easy method is converting the pem in crt

`openssl x509 -outform der -in ca.pem -out ca.crt`

Start a http server 

`python -m SimpleHTTPServer `

Go to the browser and donwload the file 

Go to Settings -> Security -> Install from SD card and click on the crt file

**Comment by trisk** [comment]
I wonder if node-http-mitm-proxy can save its root cert in other formats. Is this conversion for iOS? My Android devices accepted the ca.pem directly via "Settings -> Security -> Install from storage".

It would be nice if the proxy could act as a web server for the cert files directly, but that requires some upstream work on node-http-mitm-proxy.

**Comment by johyphenel** [comment]
@jpfelgueiras Thanks for the python tip, much cleaner than emailing to myself.
