### ISSUE TITLE
New rules from Niantic for API

### ISSUE THREAD

**Issue by btimo** [rastapasta/pokemon-go-mitm#69]
Hey, just to let you know:
https://fevgames.net/pokemon-go-apk-teardown-0-31-0/

**Comment by rubenvereecken** [comment]
Yo @btimo thanks for the heads up.

I'd just like to highlight this then

>Additionally, we saw the addition of SSL Pinning. The NianticTrustManager was added which enforces that a valid SSL certificate is used when talking with Niantic’s servers. What does this mean for you? No longer can you use a bogus certificate in order to inspect/watch traffic while the app runs. The common use case for this lately has been IV checkers and Poke scanners. Those were technically against the Terms of Service, so now breaking the ToS has been made a bit harder.

Looks like we need to mod ourselves an APK.

**Comment by trisk** [comment]
Indeed, cert pinning is going to be the biggest roadblock. I've tried to avoid looking at the app at all, though this was kind of inevitable. Using Xposed to intercept the TrustManager or JNI wrapper might be sufficient, without having to LD_PRELOAD over native code.

**Comment by ur0** [comment]
@rubenvereecken, @trisk I reversed the SSL pinning. Check [this](https://www.reddit.com/r/pokemongodev/comments/4vfyoq/pokemon_go_0310_apk_with_no_ssl_pinning/) out.

**Comment by csanonymus** [comment]
@ur0 your post has been deleted.. Can you repost somewhere else?

**Comment by btimo** [comment]
I think @ur0 did this: https://www.reddit.com/r/pokemongodev/comments/4vg3pq/reverse_engineering_and_removing_pok%C3%A9mon_gos/

**Comment by ur0** [comment]
@csanonymus, there you go: https://goo.gl/XFzgrX

r/PokemonGoDev is only getting weird.

**Comment by csanonymus** [comment]
@ur0 How do you actually set it up? I cloned this repo, installed everything, started the proxy server and updated my proxy settings in Android using both the wifi settings(didn't work) and then ProxyDroid and the app says it failed to log in. And I doing something wrong?

**Comment by jmoriau** [comment]
Mila432 showed that it seems to be as easy on iOS [()](https://www.reddit.com/r/pokemongodev/comments/4vg3pq/reverse_engineering_and_removing_pok%C3%A9mon_gos/d5yck7m) maybe someone can do the same for iOS and give us a patched IPA that we can resign individually with XCode. Would be nice <3

Anyway in the meantime the old 1.0.2 IPA still works fine.

**Comment by rastapasta** [comment]
Just finished an Xposed module which always restores the expected chain of trust - always feeding the native functions with the certificate chain they would expected. Tested - works - #win 😄 
https://github.com/rastapasta/pokemon-go-xposed

**Comment by rastapasta** [comment]
Added an .apk, putting it to xda-developers to get it into the xposed repo
Another nice side effect: you won't need to install a root certificate anymore.

Actually thinking about intercepting the network queries on the device to get the MITM either on the android or onto a running server somewhere to do the processing ... hummm .. just discovered a new field to play 😄

**Comment by btimo** [comment]
> Actually thinking about intercepting the network queries on the device to get the MITM either on the android or onto a running server somewhere to do the processing

@rastapasta take a look at https://github.com/justinleewells/pogo-optimizer

**Comment by trisk** [comment]
@rastapasta nice work, I had just created `checkClientTrusted/checkServerTrusted` interposers but you were way ahead!

**Comment by jmoriau** [comment]
@rastapasta just tried it worked flawlessly <3

**Comment by azgul** [comment]
@rastapasta the idea about intercepting (and altering) the network calls directly on the device struck my mind when I saw your xposed module too! Any idea how much it would take to get a project like that on its way? I'm an Android dev myself and I could throw a few hours at it, but I have limited low level knowledge.

**Comment by trisk** [comment]
@btimo pogo-optimizer uses this project as its backend. :)

**Comment by ilendemli** [comment]
I looked into the header files from the iOS app and managed to do something similar on my phone.
As you said @rastapasta i do not even have to install a root certificate anymore :)

Here are the few lines needed:
`%hook NIATrustedCertificatesAuthenticator

-(void)URLSession:(NSURLSession *)session didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition, NSURLCredential * _Nullable))completionHandler {
    NSURLCredential *credential = [NSURLCredential credentialForTrust:challenge.protectionSpace.serverTrust];

    completionHandler(NSURLSessionAuthChallengeUseCredential, credential);
}

%end`

**Comment by rastapasta** [comment]
@azgul let's brainstorm 😄  i gonna have heaps of free time in the coming week, up for coding!
@ilendemli that's awesome!!! i got a couple of questions for iPhone solutions, would u be up for writing a tutorial or is this a module for a framework similar to Android's Xposed? would love to see that in the hands of the community :) great job done, sir!

**Comment by ilendemli** [comment]
@rastapasta there is actually no tutorial needed, this code only works on jailbroken devices or on self injected and self signed ipa files anyway. I can just create a package, which you (or I) can submit to BigBoss if you want.

BigBoss is a repo for distributing packages over Cydia
Cydia is a package manager for jailbroken iDevices

**Comment by RollTideDG** [comment]
@ilendemli Could you explain where to put your code on iOS? I am running a jailbroken device. If not I will wait until you can get it into the BigBoss repo.

**Comment by ilendemli** [comment]
@RollTideDG i am not going to submit it to BigBoss but I have pushed it to GitHub here: https://github.com/ilendemli/trustme
You can download the deb from the packages folder. Please confirm if it works for you.

@rastapasta can you update the ReadMe and add a link to the deb file?

**Comment by rastapasta** [comment]
@ilendemli sure will do! is there any information needed? just "on a jailbroken iPhone, install this"? any requirements? (sorry, am not in the iPhone world)

**Comment by ilendemli** [comment]
@rastapasta no requirements, they will know what they are doing and how to install it, if not then they shouldn't jailbreak at all

**Comment by bactino** [comment]
possible to have a vidéo tutorial

**Comment by rastapasta** [comment]
closing issue, solved with @ilendemli 's [trustme](https://github.com/ilendemli/trustme) and [pokemon-go-xposed](https://github.com/rastapasta/pokemon-go-xposed)

**Comment by trisk** [comment]
For today's 0.33.0 release, here is a patched APK with the cert pinning disabled (currently untested): https://goo.gl/VH6NiM

**Comment by Atrion** [comment]
Forgive My ignorance on the subject, but if I use this app do I still need to "Generate a CA MITM certificate" and move it to phone/nox or does this replace that?

**Comment by trisk** [comment]
You still need to generate a certificate for the proxy to use, but it will normally do that by itself except on RPi where that fails for some reason. You don't need the certificate on your phone.

However, if you use other apps on your phone while the proxy is enabled on your phone, they will try to use the proxy as well and will need a certificate installed.

**Comment by Atrion** [comment]
Does that mean if i use nox with the modified apk and am only using pokemon and proxy droid i dont need it?

I will have to look up how to get that set up on my S4, i can move the file over just unsure how to set it up.

**Comment by rastapasta** [comment]
@trisk what a perfect answer, thanks a lot!
@Atrion just make sure to disable proxydruid while logging into pogo, the auth process through it is kinda bogus

**Comment by Jchavez** [comment]
Great work!

**Comment by robertmclaws** [comment]
Would it be possible for someone to post a patched version for MITMing that runs on x86? I'm trying to run this in the Visual Studio Emulator for Android.

Thanks!

**Comment by trisk** [comment]
I don't think a version of Pokémon Go for x86 currently exists. Also, GPS
spoofing is eventually going to land you in trouble.

**Comment by robertmclaws** [comment]
It does. Has for a few weeks now. Also, I'm well aware of the risks, I have test accounts for such things.

**Comment by trisk** [comment]
@robertmclaws Do you know where I can find the apk? As far as I've heard, people using x86 devices have just been using dynamic translation of the ARM build.

**Comment by Vankxr** [comment]
Does anyone have 0.37.0 APK?

**Comment by btimo** [comment]
@Vankxr http://www.apkmirror.com/apk/niantic-inc/pokemon-go/

**Comment by Vankxr** [comment]
@btimo I mean, the one with cert pinning disabled

**Comment by alexgithub92** [comment]
anyone has 0.39.0 apk cert pinning disable ?
