### ISSUE TITLE
port,i use virtual machine and i install ubuntu also i use nox

### ISSUE THREAD

**Issue by darkoulis12** [rastapasta/pokemon-go-mitm#97]
port,i use virtual machine and i install ubuntu also i use nox i want your help 
hi guys

im in last step to put the ports :D
i cant use ports
i put that at nox
![gg1](https://cloud.githubusercontent.com/assets/20539620/17385748/5d772e28-59ed-11e6-80fb-e33e598a4b31.PNG)

can help me how to add port at virtual machine(ubuntu) to sync?
Please?i want the virtual mewtwo please

**Comment by darkoulis12** [comment]
can just some1 answer please?why no1 answer?just help me for god sake
its my 1st time i run coffee...

**Comment by HaiseJr2016** [comment]
me to im new, i start to using the virtual pc, but how you do that?

**Comment by unrealshape** [comment]
https://postimg.org/image/f10qlyrfr/

my screen coffescript do nothing :-(

**Comment by rastapasta** [comment]
@darkoulis12 your proxy hostname must be the ip of the machine running the server - this might help :)
